-- ═══════════════════════════════════════════════════════════════════════
-- CREDIT CARD SEED DATA
-- Run in Supabase SQL Editor after schema.sql (including the
-- CREDIT_CARDS PRODUCT-PAGE FIELDS + SLUG migration block).
--
-- Sourced from each bank's own product page, cross-referenced against
-- creditcardgenius.ca for fields banks don't publish themselves
-- (mainly minimum credit score). Foreign transaction fee is not stated
-- by either source for most cards — 2.5% is applied as the Canadian
-- Visa/Mastercard industry-standard rate, not a per-card sourced figure.
--
-- affiliate_link is left NULL until CJ/Fintel/etc approvals come through.
-- is_active is TRUE so cards are browsable now; the app falls back to
-- linking "Apply Now" straight to the bank's own page when
-- affiliate_link is NULL. Set is_active = false to pull a card from
-- Explore entirely (e.g. if an affiliate application is rejected).
--
-- Uses ON CONFLICT (slug) so this file can be safely re-run as more
-- batches are appended below.
-- ═══════════════════════════════════════════════════════════════════════

-- ─── TD BANK (10 cards) ───────────────────────────────────────────────

insert into credit_cards (
  slug, name, bank, network, card_type, annual_fee, annual_fee_note,
  purchase_rate, welcome_bonus_text, min_spend_amount, min_spend_period,
  reward_type, reward_program, rewards, insurance, lounge_access, lounge_details,
  min_credit_score, income_req, is_featured, featured_bonus_text,
  affiliate_link, card_highlights, balance_transfer, is_active,
  foreign_transaction_fee, instant_approval
) values

('td-cash-back-visa-infinite', 'TD Cash Back Visa Infinite Card', 'TD Bank', 'Visa', 'cashback',
 139, '$139/yr (waived 1st year)', 21.99,
 'Earn up to $600 total value — 10% Cash Back Dollars on up to $3,500 in bonus-eligible purchases in the first 3 months',
 3500, 'first 3 months',
 'cashback', 'TD Cash Back Dollars',
 '{"groceries": 3, "gas": 3, "transit": 3, "bills": 3, "streaming": 3, "other": 1}'::jsonb,
 '["Travel Medical Insurance (10 days, 4 days if 65+)", "Delayed/Lost Baggage Insurance ($1,000)", "Purchase Security & Extended Warranty (90 days)", "Mobile Device Insurance ($1,000)", "Auto Rental Collision/Loss Damage Insurance", "Emergency Travel Assistance"]'::jsonb,
 false, null,
 'Good (660-724)', '$60,000 personal / $100,000 household', false, null,
 null,
 '["3% cash back on groceries, gas, transit, streaming & bills (up to $15,000/category/yr)", "Free Deluxe TD Auto Club Membership with roadside assistance", "Strong insurance package for a cash back card"]'::jsonb,
 false, true, 2.5, false),

('td-cash-back-visa', 'TD Cash Back Visa Card', 'TD Bank', 'Visa', 'cashback',
 0, null, 21.99,
 'Earn up to $100 in Cash Back Dollars — $20 on first purchase plus $80 when you reach $1,500 spend in the first 3 months',
 1500, 'first 3 months',
 'cashback', 'TD Cash Back Dollars',
 '{"groceries": 1, "gas": 1, "transit": 1, "bills": 1, "streaming": 1, "other": 0.5}'::jsonb,
 '["Purchase Security & Extended Warranty Protection"]'::jsonb,
 false, null,
 'Good (660-724)', null, false, null,
 null,
 '["No annual fee", "1% cash back on groceries, gas, transit, streaming & bills (up to $5,000/category/yr)"]'::jsonb,
 false, true, 2.5, false),

('td-aeroplan-visa-infinite', 'TD Aeroplan Visa Infinite Card', 'TD Bank', 'Visa', 'travel',
 139, '$139/yr (rebated 1st year)', 21.99,
 'Up to 40,000 Aeroplan points — 10,000 after first purchase, 15,000 at $3,000 spend in 90 days, 15,000 anniversary bonus at $12,000 spend in 12 months',
 3000, 'first 90 days',
 'points', 'Aeroplan',
 '{"groceries": 1.5, "gas": 1.5, "air_canada": 1.5, "other": 1}'::jsonb,
 '["Travel Medical Insurance ($2M, 21 days)", "Trip Cancellation/Interruption Insurance", "Flight/Trip Delay Insurance ($500)", "Baggage Insurance", "NEXUS fee rebate (up to $100 CAD)"]'::jsonb,
 false, null,
 'Excellent (725-759)', '$60,000 personal / $100,000 household', false, null,
 null,
 '["First checked bag free for cardholder + up to 8 companions on Air Canada", "NEXUS application fee rebate", "Strong Aeroplan earn rate on everyday categories"]'::jsonb,
 false, true, 2.5, false),

('td-aeroplan-visa-platinum', 'TD Aeroplan Visa Platinum Card', 'TD Bank', 'Visa', 'travel',
 89, '$89/yr (rebated 1st year)', 21.99,
 'Up to 20,000 Aeroplan points with $1,500 spend in the first 90 days',
 1500, 'first 90 days',
 'points', 'Aeroplan',
 '{"groceries": 1, "gas": 1, "air_canada": 1, "other": 0.67}'::jsonb,
 '["Delayed/Lost Baggage Insurance ($1,000)", "Flight/Trip Delay Insurance ($500)", "Common Carrier Travel Accident Insurance ($500,000)", "Auto Rental Collision Insurance", "Mobile Device Insurance ($1,000)"]'::jsonb,
 false, null,
 'Good (660-724)', null, false, null,
 null,
 '["Lower-fee entry point into TD''s Aeroplan lineup"]'::jsonb,
 false, true, 2.5, false),

('td-aeroplan-visa-infinite-privilege', 'TD Aeroplan Visa Infinite Privilege Card', 'TD Bank', 'Visa', 'premium',
 599, null, 21.99,
 'Up to 85,000 Aeroplan points — 20,000 on first purchase, 35,000 at $12,000 spend in 180 days, 30,000 at $24,000 spend in 12 months',
 12000, 'first 180 days',
 'points', 'Aeroplan',
 '{"air_canada": 2, "groceries": 1.5, "gas": 1.5, "travel": 1.5, "dining": 1.5, "other": 1.25}'::jsonb,
 '["Travel Medical Insurance ($5M, 31 days)", "Trip Cancellation/Interruption Insurance", "Flight/Trip Delay Insurance", "Baggage Insurance", "Auto Rental Collision Insurance", "Mobile Device Insurance ($1,500)", "NEXUS fee rebate (up to $100 CAD every 48 months)"]'::jsonb,
 true, 'Unlimited Maple Leaf Lounge access + 1 guest; 6 complimentary visits/year via Visa Airport Companion Program',
 'Excellent (725-759)', '$150,000 personal / $200,000 household', false, null,
 null,
 '["Unlimited Maple Leaf Lounge access", "Highest Aeroplan welcome bonus among TD''s cards", "2x points direct with Air Canada and Hyatt"]'::jsonb,
 false, true, 2.5, false),

('td-first-class-travel-visa-infinite', 'TD First Class Travel Visa Infinite Card', 'TD Bank', 'Visa', 'travel',
 139, '$139/yr (waived 1st year)', 21.99,
 '20,000 TD Rewards Points on first purchase + up to 126,000 points at $7,500 spend in 180 days',
 7500, 'first 180 days',
 'points', 'TD Rewards',
 '{"travel": 8, "groceries": 6, "dining": 6, "transit": 6, "streaming": 4, "bills": 4, "other": 2}'::jsonb,
 '["Trip Cancellation/Interruption Insurance ($1,500-$5,000)", "Travel Medical Insurance ($2M, 21 days)", "Flight Delay Insurance ($500)", "Baggage Insurance ($1,000)", "Auto Rental Collision Insurance"]'::jsonb,
 true, '4 complimentary visits/year via Visa Airport Companion Program (1,200+ global lounges)',
 'Good (660-724)', '$60,000 personal / $100,000 household', false, null,
 null,
 '["8x points on travel booked via Expedia For TD", "$100 annual TD Travel Credit", "4 airport lounge visits per year"]'::jsonb,
 false, true, 2.5, false),

('td-platinum-travel-visa', 'TD Platinum Travel Visa Card', 'TD Bank', 'Visa', 'travel',
 89, '$89/yr (rebated 1st year)', 21.99,
 'Up to $370 value, including up to 50,000 TD Rewards Points, with $3,000 spend in 180 days',
 3000, 'first 180 days',
 'points', 'TD Rewards',
 '{"travel": 6, "groceries": 4.5, "dining": 4.5, "transit": 4.5, "bills": 3, "streaming": 3, "other": 1.5}'::jsonb,
 '["Flight/Trip Delay Insurance ($500)", "Delayed/Lost Baggage Insurance ($1,000)", "Common Carrier Travel Accident Insurance ($500,000)", "Auto Rental Collision Insurance", "Hotel Burglary Insurance ($2,500)"]'::jsonb,
 false, null,
 'Good (660-724)', null, false, null,
 null,
 '["Mid-tier travel rewards card with a rebateable annual fee"]'::jsonb,
 false, true, 2.5, false),

('td-rewards-visa', 'TD Rewards Visa Card', 'TD Bank', 'Visa', 'rewards',
 0, null, 21.99,
 '30,310 TD Rewards Points (~$100 value) with $1,500 spend in 90 days',
 1500, 'first 90 days',
 'points', 'TD Rewards',
 '{"travel": 4, "groceries": 3, "dining": 3, "transit": 3, "bills": 2, "streaming": 2, "other": 1}'::jsonb,
 '["Mobile Device Insurance ($1,000)", "Purchase Security & Extended Warranty Protection"]'::jsonb,
 false, null,
 'Good (660-724)', null, false, null,
 null,
 '["No annual fee with a real travel-point earn rate"]'::jsonb,
 false, true, 2.5, false),

('td-low-rate-visa', 'TD Low Rate Visa Card', 'TD Bank', 'Visa', 'low_interest',
 25, null, 12.90,
 '0% promotional interest rate on purchases for the first 6 months, plus first-year annual fee rebate',
 null, null,
 'none', 'None',
 '{}'::jsonb,
 '["Purchase Security & Extended Warranty Protection (90 days, may double manufacturer warranty up to 12 months)"]'::jsonb,
 false, null,
 'Fair (560-659)', 'No minimum income requirement', false, null,
 null,
 '["12.90% ongoing rate — well below the ~21-23% most cards charge", "0% intro rate on purchases for 6 months"]'::jsonb,
 false, true, 2.5, false),

('td-us-dollar-visa', 'TD U.S. Dollar Visa Card', 'TD Bank', 'Visa', 'travel',
 39, '$39 USD/yr', 21.99,
 null, null, null,
 'none', 'None',
 '{}'::jsonb,
 '["Trip Interruption Insurance ($5,000/person)", "Common Carrier Travel Accident Insurance ($500,000)", "Delayed/Lost Baggage Insurance ($1,000)", "Auto Rental Collision Insurance", "Purchase Security & Extended Warranty Protection"]'::jsonb,
 false, null,
 'Excellent (760-900)', null, false, null,
 null,
 '["No currency conversion fee on USD purchases — useful for frequent US spenders"]'::jsonb,
 false, true, 0, false)

on conflict (slug) do update set
  name = excluded.name, bank = excluded.bank, network = excluded.network,
  card_type = excluded.card_type, annual_fee = excluded.annual_fee,
  annual_fee_note = excluded.annual_fee_note, purchase_rate = excluded.purchase_rate,
  welcome_bonus_text = excluded.welcome_bonus_text, min_spend_amount = excluded.min_spend_amount,
  min_spend_period = excluded.min_spend_period, reward_type = excluded.reward_type,
  reward_program = excluded.reward_program, rewards = excluded.rewards,
  insurance = excluded.insurance, lounge_access = excluded.lounge_access,
  lounge_details = excluded.lounge_details, min_credit_score = excluded.min_credit_score,
  income_req = excluded.income_req, is_featured = excluded.is_featured,
  featured_bonus_text = excluded.featured_bonus_text, card_highlights = excluded.card_highlights,
  balance_transfer = excluded.balance_transfer, is_active = excluded.is_active,
  foreign_transaction_fee = excluded.foreign_transaction_fee,
  instant_approval = excluded.instant_approval;

-- ─── BMO (13 cards — BMO Prepaid Mastercard excluded, not a credit product) ──

insert into credit_cards (
  slug, name, bank, network, card_type, annual_fee, annual_fee_note,
  purchase_rate, welcome_bonus_text, min_spend_amount, min_spend_period,
  reward_type, reward_program, rewards, insurance, lounge_access, lounge_details,
  min_credit_score, income_req, is_featured, featured_bonus_text,
  affiliate_link, card_highlights, balance_transfer, bt_rate, bt_months, bt_fee,
  is_active, foreign_transaction_fee, instant_approval, fees
) values

('bmo-eclipse-visa-infinite', 'BMO Eclipse Visa Infinite Card', 'BMO', 'Visa', 'rewards',
 120, '$120/yr (waived 1st year)', 21.99,
 'Up to 80,000 BMO Rewards points — 30,000 at $4,000 spend in 110 days, 20,000 at $7,000 spend in 180 days, 20,000 at $12,000 spend in 1st year',
 4000, 'first 110 days',
 'points', 'BMO Rewards',
 '{"dining": 5, "groceries": 5, "gas": 5, "transit": 5, "other": 1}'::jsonb,
 '["Mobile Device Insurance ($1,000)", "Travel Accident Insurance ($500,000)", "Emergency Medical Insurance ($5,000,000)", "Rental Car Theft & Damage Coverage", "Purchase Protection (90 days)", "Extended Warranty (1 year)"]'::jsonb,
 false, null,
 'Good (660-724)', '$60,000 personal / $100,000 household', false, null,
 null,
 '["5x points on dining, groceries, gas & transit (up to $6,000/yr each on dining & groceries)", "10% bonus points for adding an authorized user", "First-year fee waived"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$120/yr (waived 1st year)"}, {"label": "Cash advance", "value": "23.99% (21.99% in Quebec)"}]'::jsonb),

('bmo-eclipse-rise-visa', 'BMO Eclipse Rise Visa Card', 'BMO', 'Visa', 'rewards',
 0, null, 21.99,
 'Up to 20,000 BMO Rewards points (~$134 value) with $1,500 spend in first 3 months',
 1500, 'first 3 months',
 'points', 'BMO Rewards',
 '{"dining": 2.5, "groceries": 2.5, "bills": 2.5, "other": 0.5}'::jsonb,
 '["Mobile Device Insurance ($1,000)", "Extended Warranty (1 year)", "Purchase Protection (90 days)"]'::jsonb,
 false, null,
 'Good (660-724)', null, false, null,
 null,
 '["No annual fee", "2,500 bonus points for 12 months of on-time payments", "3 months free Instacart+ plus $5/mo credit"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Balance transfer intro rate", "value": "0.99% for 9 months (2% fee)"}]'::jsonb),

('bmo-ascend-world-elite-mastercard', 'BMO Ascend World Elite Mastercard', 'BMO', 'Mastercard', 'travel',
 150, '$150/yr (waived 1st year)', 21.99,
 'Up to 100,000 BMO Rewards points with $5,000 spend in first 110 days plus additional spending thresholds',
 5000, 'first 110 days',
 'points', 'BMO Rewards',
 '{"travel": 5, "dining": 3, "entertainment": 3, "bills": 3, "other": 1}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)", "Travel Accident Insurance ($500,000)", "Emergency Medical Insurance ($5,000,000)", "Trip Cancellation/Interruption Insurance", "Flight & Baggage Delay Protection", "Lost/Stolen Baggage Coverage", "Hotel Burglary Insurance", "Rental Car Theft & Damage Coverage"]'::jsonb,
 true, '4 lounge passes/year via complimentary Mastercard Travel Pass membership',
 'Good (660-724)', '$80,000 personal / $150,000 household', false, null,
 null,
 '["12 types of insurance coverage — one of BMO''s most comprehensive packages", "5x points on travel", "4 airport lounge passes/year via Mastercard Travel Pass"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$150/yr (waived 1st year)"}, {"label": "Cash advance", "value": "23.99% (21.99% in Quebec)"}]'::jsonb),

('bmo-eclipse-visa-infinite-privilege', 'BMO Eclipse Visa Infinite Privilege Card', 'BMO', 'Visa', 'premium',
 599, '$599/yr ($99/additional cardholder)', 21.99,
 'Up to 200,000 BMO Rewards points — $6,000 spend in 3 months, $30,000 in 6 months, $75,000 in first year',
 6000, 'first 3 months',
 'points', 'BMO Rewards',
 '{"travel": 5, "dining": 5, "gas": 5, "groceries": 5, "drugstore": 5, "other": 1}'::jsonb,
 '["Extended Warranty (2 years)", "Trip Cancellation Insurance ($2,500)", "Emergency Medical Insurance ($5,000,000)", "Mobile Device Protection ($1,000)", "Travel Accident Insurance ($500,000)", "Rental Car Theft & Damage Coverage"]'::jsonb,
 true, 'Complimentary Visa Airport Companion membership with 6 lounge visits/year',
 'Excellent (760-900)', '$150,000 personal / $200,000 household', false, null,
 null,
 '["5x points across travel, dining, gas, groceries & drugstore", "6 airport lounge visits per year", "25% bonus points for adding an authorized user"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$599/yr ($99/additional cardholder)"}, {"label": "Cash advance", "value": "23.99%"}]'::jsonb),

('bmo-cashback-mastercard', 'BMO CashBack Mastercard', 'BMO', 'Mastercard', 'cashback',
 0, null, 21.99,
 'Up to 5% cash back in first 3 months on up to $2,500 spend (~$100 value)',
 2500, 'first 3 months',
 'cashback', 'BMO CashBack',
 '{"groceries": 3, "bills": 1, "other": 0.5}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)"]'::jsonb,
 false, null,
 'Good (660-724)', null, false, null,
 null,
 '["No annual fee", "3% cash back on groceries (up to $500/mo)", "Redeem cash back anytime, no minimum"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Cash advance", "value": "23.99% (21.99% in Quebec)"}]'::jsonb),

('bmo-preferred-rate-mastercard', 'BMO Preferred Rate Mastercard', 'BMO', 'Mastercard', 'low_interest',
 29, '$29/yr (waived 1st year)', 13.99,
 null, null, null,
 'none', 'None',
 '{}'::jsonb,
 '["Purchase Protection (90 days)", "Extended Warranty (1 year)", "Zero Dollar Liability"]'::jsonb,
 false, null,
 'Fair (560-659)', 'No minimum income requirement', false, null,
 null,
 '["13.99% ongoing purchase rate — one of BMO''s lowest", "0% promotional rate on balance transfers for 18 months (2% fee)"]'::jsonb,
 true, 0, 18, 2,
 true, 2.5, true,
 '[{"label": "Annual fee", "value": "$29/yr (waived 1st year)"}, {"label": "Cash advance", "value": "15.99%"}, {"label": "Balance transfer fee", "value": "2% (0% promo rate for 18 months)"}]'::jsonb),

('bmo-cashback-world-elite-mastercard', 'BMO CashBack World Elite Mastercard', 'BMO', 'Mastercard', 'cashback',
 139, '$139/yr (waived 1st year)', 21.99,
 'Up to $480 cash back in first 12 months',
 null, null,
 'cashback', 'BMO CashBack',
 '{"groceries": 5, "transit": 4, "gas": 3, "bills": 2, "other": 1}'::jsonb,
 '["Travel Accident Insurance ($500,000)", "Emergency Medical Insurance", "Trip Interruption Insurance", "Flight & Baggage Delay Insurance", "Personal Effects Insurance ($750)", "Rental Car Coverage"]'::jsonb,
 false, 'Mastercard Travel Pass membership by DragonPass included (lounge access on a pay-per-visit basis)',
 'Good (660-724)', '$80,000 personal / $150,000 household', false, null,
 null,
 '["5% cash back on groceries (up to $500/mo)", "11 types of insurance coverage", "Mastercard Travel Pass by DragonPass included"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$139/yr (waived 1st year)"}, {"label": "Cash advance", "value": "23.99% (21.99% in Quebec)"}]'::jsonb),

('bmo-us-dollar-mastercard', 'BMO U.S. Dollar Mastercard', 'BMO', 'Mastercard', 'travel',
 49, 'US$49/yr (waivable with US$3,000+ annual spend)', 21.99,
 null, null, null,
 'none', 'None',
 '{}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)"]'::jsonb,
 false, null,
 'Good (660-724)', null, false, null,
 null,
 '["No foreign transaction fee on USD purchases", "Requires a BMO USD bank account to pay the bill"]'::jsonb,
 false, null, null, null,
 true, 0, false,
 '[{"label": "Annual fee", "value": "US$49/yr (waivable)"}]'::jsonb),

('bmo-student-cashback-mastercard', 'BMO CashBack Mastercard for Students', 'BMO', 'Mastercard', 'cashback',
 0, null, 21.99,
 '5% cash back in first 3 months on up to $2,500 spend (~$100 value)',
 2500, 'first 3 months',
 'cashback', 'BMO CashBack',
 '{"groceries": 3, "bills": 1, "other": 0.5}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)"]'::jsonb,
 false, null,
 'Poor to Fair (300-559)', null, false, null,
 null,
 '["Designed for students building credit for the first time", "No annual fee", "3% cash back on groceries"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}]'::jsonb),

('bmo-viporter-mastercard', 'BMO VIPorter Mastercard', 'BMO', 'Mastercard', 'travel',
 89, '$89/yr (waived 1st year)', 21.99,
 'Up to 40,000 VIPorter points (~$800 value) with tiered spending over the first year',
 null, 'first year (tiered)',
 'points', 'VIPorter Points',
 '{"porter": 2, "gas": 1, "transit": 1, "groceries": 1, "dining": 1, "other": 0.5}'::jsonb,
 '["Travel Accident Insurance ($500,000)", "Emergency Medical Insurance ($5,000,000)", "Flight Delay Insurance ($500)", "Baggage Delay Insurance ($500)", "Purchase Protection (90 days)", "Extended Warranty (1 year)"]'::jsonb,
 false, null,
 'Good (660-724)', null, false, null,
 null,
 '["Automatic VIPorter Passport Avid Traveller status", "2x points on Porter Airlines purchases", "35% flight discount after $25,000 annual spend"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$89/yr (waived 1st year)"}]'::jsonb),

('bmo-blue-rewards-world-elite-mastercard', 'BMO Blue Rewards World Elite Mastercard', 'BMO', 'Mastercard', 'rewards',
 150, '$150/yr (waived 1st year)', 21.99,
 'Up to 100,000 points (~$670 value) — $5,000 spend in 110 days, $10,000 in 6 months, $20,000 in 1st year',
 5000, 'first 110 days',
 'points', 'Blue Rewards',
 '{"blue_rewards_partners": 10, "groceries": 2, "gas": 2, "other": 1}'::jsonb,
 '["Travel Accident Insurance ($500,000)", "Emergency Medical Insurance ($2,000,000)", "Trip Cancellation Insurance ($1,500)", "Extended Warranty (1 year)", "Purchase Protection (90 days)", "Rental Car Theft/Damage Coverage"]'::jsonb,
 true, '4 lounge passes/year via Mastercard Travel Pass membership',
 'Good (660-724)', '$80,000 personal / $150,000 household', false, null,
 null,
 '["10x points at Blue Rewards partners (incl. Dollarama)", "4 airport lounge passes/year", "Free roadside assistance"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$150/yr (waived 1st year)"}]'::jsonb),

('bmo-viporter-world-elite-mastercard', 'BMO VIPorter World Elite Mastercard', 'BMO', 'Mastercard', 'travel',
 199, '$199/yr (waived 1st year)', 21.99,
 'Up to 70,000 VIPorter points (~$1,400 value) plus companion pass — tiered spending $5,000/110 days, $9,000/6mo, $18,000/1yr',
 5000, 'first 110 days',
 'points', 'VIPorter Points',
 '{"porter": 3, "gas": 2, "transit": 2, "groceries": 2, "dining": 2, "other": 1}'::jsonb,
 '["Travel Accident Insurance ($500,000)", "Emergency Medical Insurance ($5,000,000)", "Trip Cancellation Insurance ($1,500)", "Baggage Coverage", "Extended Warranty (1 year)", "Purchase Protection (90 days)"]'::jsonb,
 false, null,
 'Fair (560-659)', '$80,000 personal / $150,000 household', false, null,
 null,
 '["Automatic VIPorter Venture Avid Traveller status", "Annual companion pass after $50,000 spend", "3x points on Porter Airlines purchases"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$199/yr (waived 1st year)"}]'::jsonb),

('bmo-blue-rewards-mastercard', 'BMO Blue Rewards Mastercard', 'BMO', 'Mastercard', 'rewards',
 0, null, 21.99,
 '20,000 points (~$134 value) with $1,500 spend in first 110 days',
 1500, 'first 110 days',
 'points', 'Blue Rewards',
 '{"blue_rewards_partners": 5, "groceries": 1, "gas": 1, "other": 0.5}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)"]'::jsonb,
 false, null,
 'Fair (560-659)', null, false, null,
 null,
 '["No annual fee", "5x points at Blue Rewards partners", "Instant approval available"]'::jsonb,
 false, null, null, null,
 true, 2.5, true,
 '[{"label": "Annual fee", "value": "$0"}]'::jsonb)

on conflict (slug) do update set
  name = excluded.name, bank = excluded.bank, network = excluded.network,
  card_type = excluded.card_type, annual_fee = excluded.annual_fee,
  annual_fee_note = excluded.annual_fee_note, purchase_rate = excluded.purchase_rate,
  welcome_bonus_text = excluded.welcome_bonus_text, min_spend_amount = excluded.min_spend_amount,
  min_spend_period = excluded.min_spend_period, reward_type = excluded.reward_type,
  reward_program = excluded.reward_program, rewards = excluded.rewards,
  insurance = excluded.insurance, lounge_access = excluded.lounge_access,
  lounge_details = excluded.lounge_details, min_credit_score = excluded.min_credit_score,
  income_req = excluded.income_req, is_featured = excluded.is_featured,
  featured_bonus_text = excluded.featured_bonus_text, card_highlights = excluded.card_highlights,
  balance_transfer = excluded.balance_transfer, bt_rate = excluded.bt_rate,
  bt_months = excluded.bt_months, bt_fee = excluded.bt_fee,
  is_active = excluded.is_active, foreign_transaction_fee = excluded.foreign_transaction_fee,
  instant_approval = excluded.instant_approval, fees = excluded.fees;

-- ─── AMERICAN EXPRESS (10 cards) ──────────────────────────────────────────
-- amex.com is consent-gated/JS-rendered like bmo.com/cibc.com — sourced
-- entirely from creditcardgenius.ca. Note: none of the original 9 mockup
-- cards (including the old "amex-cobalt" placeholder) were ever actually
-- seeded into this table, so this Cobalt row is a fresh, fully-sourced
-- replacement, not an update.

insert into credit_cards (
  slug, name, bank, network, card_type, annual_fee, annual_fee_note,
  purchase_rate, welcome_bonus_text, min_spend_amount, min_spend_period,
  reward_type, reward_program, rewards, insurance, lounge_access, lounge_details,
  min_credit_score, income_req, is_featured, featured_bonus_text,
  affiliate_link, card_highlights, balance_transfer, is_active,
  foreign_transaction_fee, instant_approval
) values

('amex-platinum', 'The Platinum Card', 'American Express', 'Amex', 'premium',
 799, null, 0,
 'Up to 100,000 Membership Rewards points — 70,000 at $10,000 spend in 3 months, 30,000 at a purchase between months 15-17',
 10000, 'first 3 months',
 'points', 'Amex MR Points',
 '{"dining": 2, "travel": 2, "other": 1}'::jsonb,
 '["Extended Warranty (1 year)", "Travel Accident Insurance ($500,000)", "Trip Cancellation Insurance ($2,500)", "11 types of insurance total"]'::jsonb,
 true, 'Unlimited access for cardholder + 1 guest to 1,400+ airport lounges',
 'Excellent (760-900)', 'No income requirement', false, null,
 null,
 '["Charge card — no preset spending limit", "$200 annual travel credit + $200 annual dining credit", "Unlimited lounge access for cardholder + 1 guest"]'::jsonb,
 false, true, 2.5, false),

('amex-gold-rewards', 'American Express Gold Rewards Card', 'American Express', 'Amex', 'rewards',
 250, null, 21.99,
 'Up to 60,000 Membership Rewards points with $1,000/mo spend in first year',
 1000, 'monthly, first year',
 'points', 'Amex MR Points',
 '{"gas": 2, "groceries": 2, "drugstore": 2, "travel": 2, "other": 1}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)", "Travel Accident Insurance ($500,000)", "11 types of insurance total"]'::jsonb,
 true, '4 free Plaza Premium lounge passes in Canada + discounted Priority Pass membership',
 'Excellent (725-759)', 'No income requirement', false, null,
 null,
 '["$100 annual travel credit", "4 free Plaza Premium lounge passes in Canada", "2x points on gas, groceries, drugstores & travel"]'::jsonb,
 false, true, 2.5, false),

('amex-aeroplan-reserve', 'American Express Aeroplan Reserve Card', 'American Express', 'Amex', 'premium',
 599, null, 21.99,
 'Up to 85,000 Aeroplan points (~$1,360 value) — $7,500 spend in 3 months + $2,500 in month 13',
 7500, 'first 3 months',
 'points', 'Aeroplan',
 '{"air_canada": 3, "dining": 2, "other": 1.25}'::jsonb,
 '["Extended Warranty (1 year)", "Travel Accident Insurance ($500,000)", "Trip Cancellation Insurance ($1,500)", "11 types of insurance total"]'::jsonb,
 true, 'Unlimited Maple Leaf Lounge access when flying Air Canada + Priority Pass membership',
 'Excellent (725-759)', 'Not stated', false, null,
 null,
 '["Unlimited Maple Leaf Lounge access on Air Canada travel days", "Free first checked bag on Air Canada", "3x Aeroplan points direct with Air Canada"]'::jsonb,
 false, true, 2.5, false),

('amex-marriott-bonvoy', 'Marriott Bonvoy American Express Card', 'American Express', 'Amex', 'travel',
 120, null, 21.99,
 'Up to 110,000 Marriott Bonvoy points — $6,000 spend in 6 months + a purchase in month 15',
 6000, 'first 6 months',
 'points', 'Marriott Bonvoy',
 '{"other": 2}'::jsonb,
 '["Travel Accident Insurance ($500,000)", "Extended Warranty (1 year)", "Purchase Protection (90 days)"]'::jsonb,
 false, null,
 'Good (660-724)', 'No income requirement', false, null,
 null,
 '["5x points at Marriott Bonvoy hotels", "Free night award (up to 35,000 points) every account anniversary", "Automatic Silver Elite status + 15 elite night credits"]'::jsonb,
 false, true, 2.5, false),

('amex-cobalt', 'American Express Cobalt Card', 'American Express', 'Amex', 'rewards',
 191.88, '$15.99/mo', 21.99,
 'Up to 15,000 points (1,250/mo) with $750/mo spend in first year',
 750, 'monthly, first year',
 'points', 'Amex MR Points',
 '{"groceries": 5, "dining": 5, "streaming": 3, "transit": 2, "gas": 2, "other": 1}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)", "Mobile Device Insurance ($1,000)", "Travel Accident Insurance ($250,000)", "Flight/Baggage Delay Insurance ($500 each)", "Hotel Burglary Insurance", "Rental Car Protection", "10 types of insurance total"]'::jsonb,
 false, null,
 'Good (660-724)', 'Not stated', false, null,
 null,
 '["Highest everyday earn rate on food & drink of any Canadian card (5x, capped $2,500/mo)", "Monthly fee spreads the cost out instead of one annual hit", "Instant approval available"]'::jsonb,
 false, true, 2.5, true),

('amex-aeroplan', 'American Express Aeroplan Card', 'American Express', 'Amex', 'travel',
 120, null, 0,
 'Up to 45,000 Aeroplan points — $7,500 spend in 6 months + 10,000 more at $1,000 spend in month 13',
 7500, 'first 6 months',
 'points', 'Aeroplan',
 '{"air_canada": 2, "dining": 1.5, "other": 1}'::jsonb,
 '["Travel Accident Insurance ($500,000)", "Flight Delay Insurance ($500)", "Baggage Delay/Lost Insurance ($500 each)", "Extended Warranty (1 year)", "Purchase Protection (90 days)"]'::jsonb,
 false, null,
 'Good (660-724)', 'Not stated', false, null,
 null,
 '["Free first checked bag for cardholder + up to 8 companions on Air Canada", "Charge card — no preset spending limit", "Preferred pricing on Aeroplan flight rewards"]'::jsonb,
 false, true, 2.5, false),

('amex-green', 'American Express Green Card', 'American Express', 'Amex', 'rewards',
 0, null, 21.99,
 '10,000 Membership Rewards points with $1,000 spend in first 3 months',
 1000, 'first 3 months',
 'points', 'Amex MR Points',
 '{"other": 1}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)"]'::jsonb,
 false, null,
 'Excellent (760-900)', 'No income requirement', false, null,
 null,
 '["No annual fee", "Points transfer to airline and hotel loyalty programs", "Amex Experiences & presale ticket access"]'::jsonb,
 false, true, 2.5, false),

('amex-simplycash-preferred', 'SimplyCash Preferred Card from American Express', 'American Express', 'Amex', 'cashback',
 119.88, '$9.99/mo', 21.99,
 '10% cash back for first 3 months on up to $2,000 spend + $50 at month 13 (~$250 value)',
 2000, 'first 3 months',
 'cashback', 'Amex Cash Back',
 '{"gas": 4, "groceries": 4, "other": 2}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)", "Mobile Device Insurance ($1,000)", "Travel Accident Insurance ($100,000)", "Emergency Medical Insurance ($5,000,000)", "Flight/Baggage Delay Insurance ($500 each)", "Hotel Burglary Insurance", "Rental Car Theft & Damage"]'::jsonb,
 false, null,
 'Excellent (725-759)', 'No income requirement', false, null,
 null,
 '["4% cash back on gas & groceries — high flat rate, no rotating categories", "Instant approval available", "Cash back paid annually as a statement credit"]'::jsonb,
 false, true, 2.5, true),

('amex-simplycash', 'SimplyCash Card from American Express', 'American Express', 'Amex', 'cashback',
 0, null, 21.99,
 '5% cash back on all purchases for first 3 months (up to $100)',
 null, 'first 3 months',
 'cashback', 'Amex Cash Back',
 '{"gas": 2, "groceries": 2, "other": 1.25}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)", "Travel Accident Insurance ($100,000)"]'::jsonb,
 false, null,
 'Good (660-724)', 'No income requirement', false, null,
 null,
 '["No annual fee", "2% cash back on gas & groceries (groceries capped $300/yr)", "Cash back paid annually as a statement credit"]'::jsonb,
 false, true, 2.5, false),

('amex-essential', 'American Express Essential Credit Card', 'American Express', 'Amex', 'low_interest',
 25, null, 12.99,
 null, null, null,
 'none', 'None',
 '{}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)", "Travel Accident Insurance ($100,000)"]'::jsonb,
 false, null,
 'Excellent (760-900)', 'No income requirement', false, null,
 null,
 '["12.99% ongoing rate — low for an Amex card", "No rewards program — built for carrying a balance, not earning points"]'::jsonb,
 false, true, 2.5, false)

on conflict (slug) do update set
  name = excluded.name, bank = excluded.bank, network = excluded.network,
  card_type = excluded.card_type, annual_fee = excluded.annual_fee,
  annual_fee_note = excluded.annual_fee_note, purchase_rate = excluded.purchase_rate,
  welcome_bonus_text = excluded.welcome_bonus_text, min_spend_amount = excluded.min_spend_amount,
  min_spend_period = excluded.min_spend_period, reward_type = excluded.reward_type,
  reward_program = excluded.reward_program, rewards = excluded.rewards,
  insurance = excluded.insurance, lounge_access = excluded.lounge_access,
  lounge_details = excluded.lounge_details, min_credit_score = excluded.min_credit_score,
  income_req = excluded.income_req, is_featured = excluded.is_featured,
  featured_bonus_text = excluded.featured_bonus_text, card_highlights = excluded.card_highlights,
  balance_transfer = excluded.balance_transfer, is_active = excluded.is_active,
  foreign_transaction_fee = excluded.foreign_transaction_fee,
  instant_approval = excluded.instant_approval;

-- ─── RBC (16 cards) ───────────────────────────────────────────────────────
-- Sourced from rbcroyalbank.com directly (fetchable, unlike bmo.com/cibc.com);
-- credit score cross-referenced from creditcardgenius.ca as usual.

insert into credit_cards (
  slug, name, bank, network, card_type, annual_fee, annual_fee_note,
  purchase_rate, welcome_bonus_text, min_spend_amount, min_spend_period,
  reward_type, reward_program, rewards, insurance, lounge_access, lounge_details,
  min_credit_score, income_req, is_featured, featured_bonus_text,
  affiliate_link, card_highlights, balance_transfer, bt_rate, bt_months, bt_fee,
  is_active, foreign_transaction_fee, instant_approval, fees
) values

('rbc-avion-visa-infinite', 'RBC Avion Visa Infinite', 'RBC', 'Visa', 'travel',
 120, '$120/yr', 20.99,
 'Up to 70,000 Avion points — 35,000 on approval, 20,000 at $5,000 spend in 6 months, 15,000 anniversary bonus',
 5000, 'first 6 months',
 'points', 'RBC Avion',
 '{"travel": 1.25, "other": 1}'::jsonb,
 '["Emergency Medical Coverage", "Travel Accident Insurance", "Trip Cancellation/Interruption Insurance", "Auto Rental Collision/Loss Waiver", "Delayed Baggage Insurance", "Flight Delay Insurance", "Hotel Burglary Insurance", "Purchase Security & Extended Warranty", "Mobile Device Insurance"]'::jsonb,
 false, null,
 'Fair (560-659)', '$60,000 personal / $100,000 household', false, null,
 null,
 '["No foreign transaction fee", "Annual travel enhancement credit (up to $100 extra on Avion Rewards bookings $200+)", "Points worth up to 2.33¢ each depending on redemption"]'::jsonb,
 false, null, null, null,
 true, 0, false,
 '[{"label": "Annual fee", "value": "$120/yr"}, {"label": "Cash advance", "value": "22.99%"}, {"label": "Additional cardholder", "value": "$50/yr"}]'::jsonb),

('rbc-ion-plus-visa', 'RBC ION+ Visa', 'RBC', 'Visa', 'rewards',
 48, '$4/mo ($48/yr)', 20.99,
 'Up to 28,000 Avion points — 7,000 on approval, 14,000 at $1,500 spend in 6 months, 7,000 anniversary bonus',
 1500, 'first 6 months',
 'points', 'RBC Avion',
 '{"groceries": 3, "gas": 3, "dining": 3, "streaming": 3, "other": 1}'::jsonb,
 '["Mobile Device Insurance (2 years, $1,000)", "Purchase Security & Extended Warranty (up to 5 years total)"]'::jsonb,
 false, null,
 'Fair (560-659)', null, false, null,
 null,
 '["3x points on groceries, gas, dining, food delivery, rideshare & streaming", "Annual fee rebate for students/under-24 with an RBC student banking account", "Access to 2,000+ Avion Rewards partner brands"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$4/mo ($48/yr)"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('rbc-westjet-world-elite-mastercard', 'WestJet RBC World Elite Mastercard', 'RBC', 'Mastercard', 'travel',
 139, '$139/yr', 20.99,
 'Up to 70,000 WestJet points (up to $700 off travel)',
 null, null,
 'points', 'WestJet Rewards',
 '{"travel": 2, "groceries": 2, "gas": 2, "transit": 2, "other": 1.5}'::jsonb,
 '["Trip Cancellation Insurance", "Mobile Device Insurance", "Travel Accident Insurance", "Auto Rental Collision/Loss Damage", "Trip Interruption Insurance", "Purchase Security & Extended Warranty", "Delayed Baggage Insurance", "Flight Delay Insurance", "Emergency Medical Insurance", "Hotel Burglary Insurance"]'::jsonb,
 true, 'Mastercard Travel Pass via DragonPass — 1,300+ airport lounges worldwide',
 'Good (660-724)', '$80,000 personal / $150,000 household', false, null,
 null,
 '["Free checked bag for cardholder + up to 8 companions on WestJet", "Annual companion voucher (with $5,000+ annual spend)", "Priceless Cities access"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$139/yr"}, {"label": "Additional cardholder", "value": "$59/yr"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('rbc-cash-back-mastercard', 'RBC Cash Back Mastercard', 'RBC', 'Mastercard', 'cashback',
 0, null, 20.99,
 'Up to 7% cash back for first 3 months on up to $1,000 in purchases',
 1000, 'first 3 months',
 'cashback', 'RBC Cash Back',
 '{"groceries": 2, "other": 0.5}'::jsonb,
 '["Purchase Security & Extended Warranty Insurance (90 days, up to 1 extra year)"]'::jsonb,
 false, null,
 'Good (660-724)', null, false, null,
 null,
 '["No annual fee", "2% cash back on groceries (first $6,000/yr)", "NOMI financial insights included"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('rbc-cash-back-preferred-world-elite-mastercard', 'RBC Cash Back Preferred World Elite Mastercard', 'RBC', 'Mastercard', 'cashback',
 99, '$99/yr', 20.99,
 '12% cash back for first 3 months on up to $2,000 in purchases',
 2000, 'first 3 months',
 'cashback', 'RBC Cash Back',
 '{"other": 1.5}'::jsonb,
 '["Purchase Security & Extended Warranty Insurance (120 days, up to 2 extra years)", "Auto Rental Collision/Loss Damage Waiver"]'::jsonb,
 true, '1,300+ airport lounges worldwide via Mastercard World Elite DragonPass',
 'Good (660-724)', '$80,000 personal / $150,000 household', false, null,
 null,
 '["Flat 1.5% cash back on everything, no categories to track (first $25,000/yr)", "No cap on total cash back earned", "3¢/L fuel savings at Petro-Canada"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$99/yr"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('rbc-low-rate-option-visa-classic', 'RBC Visa Classic Low Rate Option', 'RBC', 'Visa', 'low_interest',
 20, '$20/yr (waived 1st year)', 12.99,
 '0.99% introductory rate on balance transfers for first 10 months',
 null, null,
 'none', 'None',
 '{}'::jsonb,
 '["Purchase Security & Extended Warranty Insurance (90 days, up to 1 extra year, max 5 years total)"]'::jsonb,
 false, null,
 'Fair (560-659)', null, false, null,
 null,
 '["12.99% ongoing rate — well below RBC''s standard ~21%", "No fee for additional cardholders"]'::jsonb,
 true, 0.99, 10, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$20/yr (waived 1st year)"}, {"label": "Cash advance", "value": "12.99%"}]'::jsonb),

('rbc-ion-visa', 'RBC ION Visa', 'RBC', 'Visa', 'rewards',
 0, null, 20.99,
 'Up to 14,000 Avion points — 7,000 on approval, 7,000 at $500 spend in 3 months',
 500, 'first 3 months',
 'points', 'RBC Avion',
 '{"groceries": 1.5, "gas": 1.5, "transit": 1.5, "streaming": 1.5, "other": 1}'::jsonb,
 '["Purchase Security & Extended Warranty Insurance (90 days, up to 1 extra year, max 5 years total)"]'::jsonb,
 false, null,
 'Fair (560-659)', null, false, null,
 null,
 '["No annual fee", "1.5x points on groceries, gas, transit, streaming & digital gaming", "Access to 2,000+ Avion Rewards partner brands"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('rbc-more-rewards-visa', 'More Rewards RBC Visa', 'RBC', 'Visa', 'rewards',
 0, null, 20.99,
 'Up to 20,000 More Rewards points (~$30 in groceries)',
 null, null,
 'points', 'More Rewards',
 '{"groceries": 5, "gas": 5, "dining": 5, "other": 3}'::jsonb,
 '["Purchase Security & Extended Warranty (90 days, up to 5 years total)", "Mobile Device Insurance ($1,000)"]'::jsonb,
 false, null,
 'Excellent (760-900)', null, false, null,
 null,
 '["5x points at 700+ Western Canadian partner stores, gas & dining", "No annual fee", "Not available in Quebec"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('rbc-moi-visa', 'moi RBC Visa', 'RBC', 'Visa', 'rewards',
 0, null, 20.99,
 'Up to 5,000 Moi bonus points (~$40 value) with $500 spend in first 3 months',
 500, 'first 3 months',
 'points', 'Moi Points',
 '{"dining": 2, "gas": 2, "other": 1}'::jsonb,
 '["Mobile Device Insurance (2 years, $1,000)", "Purchase Security & Extended Warranty (up to 5 years total)"]'::jsonb,
 false, null,
 'Excellent (760-900)', null, false, null,
 null,
 '["Quebec-focused — bonus points at Metro, Brunet, Première Moisson, Jean Coutu", "No annual fee"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Cash advance", "value": "22.99% (21.99% in Quebec)"}]'::jsonb),

('rbc-avion-visa-platinum', 'RBC Avion Visa Platinum', 'RBC', 'Visa', 'travel',
 120, '$120/yr', 20.99,
 'Up to 70,000 Avion points — 35,000 on approval, 20,000 at $5,000 spend in 6 months, 15,000 anniversary bonus',
 5000, 'first 6 months',
 'points', 'RBC Avion',
 '{"other": 1}'::jsonb,
 '["Travel Accident Insurance", "Trip Cancellation & Interruption Insurance", "Auto Rental Collision/Loss Damage Waiver Insurance", "Delayed Baggage Insurance", "Flight Delay Insurance", "Purchase Security & Extended Warranty", "Hotel/Motel Burglary Insurance"]'::jsonb,
 false, null,
 'Excellent (760-900)', null, false, null,
 null,
 '["Same welcome bonus as the Infinite tier at the same fee, but flat 1x earn rate (no travel bonus)"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$120/yr"}, {"label": "Additional cardholder", "value": "$50/yr"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('rbc-westjet-mastercard', 'WestJet RBC Mastercard', 'RBC', 'Mastercard', 'travel',
 39, '$39/yr', 20.99,
 'Up to 15,000 WestJet points (up to $150 off travel)',
 null, null,
 'points', 'WestJet Rewards',
 '{"travel": 1.5, "dining": 1.5, "streaming": 1.5, "other": 1}'::jsonb,
 '["Travel Accident Insurance", "Auto Rental Collision/Loss Damage", "Purchase Security & Extended Warranty", "Mobile Device Insurance", "Delayed Baggage Insurance", "Hotel/Motel Burglary Insurance"]'::jsonb,
 false, null,
 'Fair (560-659)', null, false, null,
 null,
 '["Annual companion voucher (requires $2,500+ annual spend)", "Lower-fee entry point into WestJet Rewards"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$39/yr"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('rbc-avion-visa-infinite-privilege', 'RBC Avion Visa Infinite Privilege', 'RBC', 'Visa', 'premium',
 399, null, 20.99,
 'Up to 100,000 Avion points (35,000 on approval, 20,000 at $5,000 spend in 6 months, 45,000 anniversary bonus) + 6 lounge passes',
 5000, 'first 6 months',
 'points', 'RBC Avion',
 '{"other": 1.25}'::jsonb,
 '["Emergency Medical Insurance", "Travel Accident Insurance", "Auto Rental Collision/Loss Damage Waiver", "Trip Cancellation/Interruption Insurance", "Delayed Baggage Insurance", "Flight Delay Insurance", "Hotel/Motel Burglary Insurance", "Purchase Security & Extended Warranty", "Mobile Device Insurance ($1,500)", "Lost/Stolen Baggage Insurance"]'::jsonb,
 true, '6 annual global lounge passes (~$375 value); airport security fast track; dedicated parking at select Canadian airports',
 'Good (660-724)', '$200,000 personal / $200,000 household', false, null,
 null,
 '["Double point value on business/first-class flight tickets", "6 lounge passes/year", "Airport fast-track security"]'::jsonb,
 false, null, null, null,
 true, 0, false,
 '[{"label": "Annual fee", "value": "$399/yr"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('rbc-british-airways-visa-infinite', 'RBC British Airways Visa Infinite', 'RBC', 'Visa', 'travel',
 165, '$165/yr', 20.50,
 'Up to 60,000 Avios (enough for a return reward flight to London from Canada)',
 null, null,
 'points', 'Avios',
 '{"dining": 2, "other": 1}'::jsonb,
 '["Travel Accident Insurance", "Emergency Medical Insurance", "Delayed Baggage Insurance", "Flight Delay Insurance", "Hotel/Motel Burglary Insurance", "Auto Rental Collision/Loss Damage Waiver", "Purchase Security & Extended Warranty"]'::jsonb,
 false, null,
 'Good (660-724)', '$60,000 personal / $100,000 household', false, null,
 null,
 '["3x Avios direct with British Airways", "Companion voucher at $30,000 annual spend", "Visa Infinite concierge service"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$165/yr"}, {"label": "Additional cardholder", "value": "$75/yr"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('rbc-visa-platinum', 'RBC Visa Platinum', 'RBC', 'Visa', 'rewards',
 0, null, 20.99,
 null, null, null,
 'none', 'None',
 '{}'::jsonb,
 '["Travel Accident Insurance", "Auto Rental Collision/Loss Damage Waiver Insurance", "Purchase Security & Extended Warranty Insurance"]'::jsonb,
 false, null,
 'Excellent (760-900)', null, false, null,
 null,
 '["No annual fee, no rewards program", "Access to Avion Rewards partner offers (Petro-Canada, Rexall, DoorDash, Triangle)", "Free additional cards"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('rbc-us-dollar-visa-gold', 'RBC U.S. Dollar Visa Gold', 'RBC', 'Visa', 'travel',
 65, 'US$65/yr', 20.99,
 null, null, null,
 'points', 'RBC Avion',
 '{"other": 1}'::jsonb,
 '["Travel Accident Insurance", "Auto Rental Collision/Loss Damage Waiver", "Trip Cancellation & Interruption Insurance", "Delayed Baggage Insurance", "Purchase Security & Extended Warranty"]'::jsonb,
 false, null,
 'Excellent (760-900)', null, false, null,
 null,
 '["USD-denominated to avoid daily currency fluctuation on US spending", "Still earns 1 Avion point per US$1 spent"]'::jsonb,
 false, null, null, null,
 true, 0, false,
 '[{"label": "Annual fee", "value": "US$65/yr"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('rbc-more-rewards-visa-infinite', 'More Rewards RBC Visa Infinite', 'RBC', 'Visa', 'rewards',
 0, null, 20.99,
 'Up to 20,000 More Rewards points (~$30 in groceries)',
 null, null,
 'points', 'More Rewards',
 '{"groceries": 8, "gas": 8, "dining": 8, "other": 4}'::jsonb,
 '["Purchase Security & Extended Warranty (90 days, up to 5 years total)", "Mobile Device Insurance (2 years, $1,000)"]'::jsonb,
 false, null,
 'Excellent (760-900)', '$60,000 personal / $100,000 household', false, null,
 null,
 '["8x points at 700+ partner stores, gas & dining — no annual fee for a Visa Infinite-tier earn rate", "Not available in Quebec"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb)

on conflict (slug) do update set
  name = excluded.name, bank = excluded.bank, network = excluded.network,
  card_type = excluded.card_type, annual_fee = excluded.annual_fee,
  annual_fee_note = excluded.annual_fee_note, purchase_rate = excluded.purchase_rate,
  welcome_bonus_text = excluded.welcome_bonus_text, min_spend_amount = excluded.min_spend_amount,
  min_spend_period = excluded.min_spend_period, reward_type = excluded.reward_type,
  reward_program = excluded.reward_program, rewards = excluded.rewards,
  insurance = excluded.insurance, lounge_access = excluded.lounge_access,
  lounge_details = excluded.lounge_details, min_credit_score = excluded.min_credit_score,
  income_req = excluded.income_req, is_featured = excluded.is_featured,
  featured_bonus_text = excluded.featured_bonus_text, card_highlights = excluded.card_highlights,
  balance_transfer = excluded.balance_transfer, bt_rate = excluded.bt_rate,
  bt_months = excluded.bt_months, bt_fee = excluded.bt_fee,
  is_active = excluded.is_active, foreign_transaction_fee = excluded.foreign_transaction_fee,
  instant_approval = excluded.instant_approval, fees = excluded.fees;

-- ─── CIBC (20 cards, incl. 5 student variants) ───────────────────────────
-- Sourced from creditcardgenius.ca (CIBC's own pages render rates via
-- client-side JS that WebFetch can't read). Student variants confirmed to
-- mirror parent cards' fees/rewards with relaxed/no income requirement.

insert into credit_cards (
  slug, name, bank, network, card_type, annual_fee, annual_fee_note,
  purchase_rate, welcome_bonus_text, min_spend_amount, min_spend_period,
  reward_type, reward_program, rewards, insurance, lounge_access, lounge_details,
  min_credit_score, income_req, is_featured, featured_bonus_text,
  affiliate_link, card_highlights, balance_transfer, bt_rate, bt_months, bt_fee,
  is_active, foreign_transaction_fee, instant_approval, fees
) values

('cibc-aventura-visa-infinite', 'CIBC Aventura Visa Infinite Card', 'CIBC', 'Visa', 'travel',
 139, '$139/yr', 21.99,
 'Up to 45,000 Aventura points (15,000 on first purchase, 30,000 at $3,000 spend in 4 months) + first-year fee rebate',
 3000, 'first 4 months',
 'points', 'CIBC Aventura',
 '{"travel": 2, "gas": 1.5, "groceries": 1.5, "drugstore": 1.5, "other": 1}'::jsonb,
 '["Trip Cancellation Insurance", "Trip Interruption Insurance", "Flight Delay Insurance", "Baggage Delay Insurance", "Mobile Device Insurance ($1,000)", "Travel Accident Insurance ($500,000)"]'::jsonb,
 true, 'Visa Airport Companion membership — 4 free passes at 1,200+ lounges',
 'Good (660-724)', '$60,000 personal / $100,000 household', false, null,
 null,
 '["NEXUS fee rebate ($160 every 4 years)", "Free Skip+ membership (first year, $110 value)", "4 airport lounge passes"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$139/yr"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('cibc-aeroplan-visa-infinite', 'CIBC Aeroplan Visa Infinite Card', 'CIBC', 'Visa', 'travel',
 139, '$139/yr (waived 1st year)', 21.99,
 '50,000 Aeroplan points (~$800 value)',
 null, null,
 'points', 'Aeroplan',
 '{"gas": 1.5, "groceries": 1.5, "air_canada": 1.5, "other": 1}'::jsonb,
 '["Extended Warranty (1 year)", "Travel Accident Insurance ($500,000)", "Emergency Medical Insurance ($5,000,000)", "Trip Cancellation Insurance ($1,500)", "Mobile Device Insurance ($1,000)"]'::jsonb,
 false, null,
 'Excellent (760-900)', '$60,000 personal / $100,000 household', false, null,
 null,
 '["Free first checked bag for cardholder + up to 8 companions", "4th night free at hotels booked through Aeroplan"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$139/yr (waived 1st year)"}, {"label": "Cash advance", "value": "22.99% (21.99% in Quebec)"}]'::jsonb),

('cibc-aventura-visa-infinite-privilege', 'CIBC Aventura Visa Infinite Privilege Card', 'CIBC', 'Visa', 'premium',
 499, null, 21.99,
 '50,000 Aventura points (~$1,832 value) with $3,000 spend in first 4 months',
 3000, 'first 4 months',
 'points', 'CIBC Aventura',
 '{"travel": 3, "gas": 2, "groceries": 2, "dining": 2, "transit": 2, "other": 1.25}'::jsonb,
 '["Travel Accident Insurance ($500,000)", "Emergency Medical Insurance ($5,000,000, 31 days)", "Trip Cancellation Insurance ($2,500)", "Trip Interruption Insurance ($5,000)", "Flight Delay Insurance ($500)", "Baggage Delay Insurance ($500)", "Lost Baggage Insurance ($1,000)", "Rental Car Theft & Damage", "Purchase Protection (180 days)", "Extended Warranty (2 years)", "Mobile Device Insurance ($1,500)"]'::jsonb,
 true, '6 complimentary Visa Airport Companion lounge visits + $200 annual travel credit',
 'Excellent (760-900)', '$150,000 personal / $200,000 household', false, null,
 null,
 '["3x points on travel booked through CIBC Rewards", "$200 annual travel credit", "6 airport lounge visits/year"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$499/yr"}, {"label": "Cash advance", "value": "22.99% (21.99% in Quebec)"}]'::jsonb),

('cibc-aeroplan-visa-infinite-privilege', 'CIBC Aeroplan Visa Infinite Privilege Card', 'CIBC', 'Visa', 'premium',
 599, null, 21.99,
 '100,000 Aeroplan points (~$1,600 value)',
 null, null,
 'points', 'Aeroplan',
 '{"air_canada": 2, "gas": 1.5, "groceries": 1.5, "dining": 1.5, "travel": 1.5, "other": 1.25}'::jsonb,
 '["Extended Warranty (2 years)", "Purchase Protection (180 days)", "Mobile Device Insurance ($1,500)", "Travel Accident Insurance ($500,000)", "Trip Cancellation Insurance ($2,500)", "Flight Delay Insurance ($1,000)", "Baggage Delay/Loss Insurance ($1,000 each)", "Rental Car Theft & Damage"]'::jsonb,
 true, 'Unlimited Maple Leaf Lounge access + 6 complimentary Visa Airport Companion visits',
 'Excellent (760-900)', '$150,000 personal / $200,000 household', false, null,
 null,
 '["Unlimited Maple Leaf Lounge access", "Free checked bag on Air Canada flights", "Preferred pricing on Aeroplan flight rewards"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$599/yr"}, {"label": "Cash advance", "value": "22.99% (21.99% in Quebec)"}]'::jsonb),

('cibc-aventura-gold-visa', 'CIBC Aventura Gold Visa Card', 'CIBC', 'Visa', 'travel',
 139, '$139/yr', 21.99,
 'Up to 45,000 Aventura points (15,000 on first purchase, 30,000 at $3,000 spend in 4 statements)',
 3000, 'first 4 statement periods',
 'points', 'CIBC Aventura',
 '{"travel": 2, "gas": 1.5, "groceries": 1.5, "drugstore": 1.5, "other": 1}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)", "Mobile Device Insurance ($1,000)", "Travel Accident Insurance ($500,000)", "Emergency Medical Insurance ($5,000,000)", "Flight Delay Insurance ($500)", "Baggage Delay Insurance ($500)", "Lost/Stolen Baggage Insurance ($500)", "Hotel Burglary Insurance ($2,500)", "Rental Car Theft & Damage"]'::jsonb,
 true, '4 complimentary visits at 1,200+ lounges via Visa Airport Companion Program',
 'Good (660-724)', '$15,000 household', false, null,
 null,
 '["Much lower income bar than the Visa Infinite tier for similar rewards", "4 airport lounge visits/year"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$139/yr"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('cibc-aventura-visa', 'CIBC Aventura Visa Card', 'CIBC', 'Visa', 'rewards',
 0, null, 21.99,
 'Up to 12,500 Aventura points (7,500 on first purchase in 4 months, 2,500 for completing 5 activities in 60 days)',
 null, 'first 4 months',
 'points', 'CIBC Aventura',
 '{"travel": 1, "gas": 1, "groceries": 1, "drugstore": 1, "other": 0.5}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)", "Travel Accident Insurance ($100,000)"]'::jsonb,
 false, null,
 'Excellent (760-900)', '$15,000 household', false, null,
 null,
 '["No annual fee", "Free Skip+ membership (first year, $110 value)", "Points never expire"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Cash advance", "value": "22.99% (21.99% in Quebec)"}]'::jsonb),

('cibc-aeroplan-visa', 'CIBC Aeroplan Visa Card', 'CIBC', 'Visa', 'rewards',
 0, null, 21.99,
 '10,000 Aeroplan points (~$160 value)',
 null, null,
 'points', 'Aeroplan',
 '{"gas": 1, "groceries": 1, "air_canada": 1, "other": 0.67}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)", "Travel Accident Insurance ($100,000)", "Rental Car Theft & Damage"]'::jsonb,
 false, null,
 'Excellent (760-900)', '$15,000 household', false, null,
 null,
 '["No annual fee entry point into Aeroplan", "3¢/L fuel savings at Journie Rewards"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Cash advance", "value": "22.99% (21.99% in Quebec)"}]'::jsonb),

('cibc-adapta-mastercard', 'CIBC Adapta Mastercard', 'CIBC', 'Mastercard', 'rewards',
 0, null, 21.99,
 'Up to 6,000 Adapta points (~$50 value) with $1,000 spend in first 4 months',
 1000, 'first 4 months',
 'points', 'CIBC Adapta',
 '{"other": 1}'::jsonb,
 '["Roadside Assistance ($50 value — battery boost, gas delivery, towing)", "Extended Warranty (1 year)", "Purchase Protection (90 days)"]'::jsonb,
 false, null,
 'Good (660-724)', '$15,000 household', false, null,
 null,
 '["Automatically earns 1.5x points in whichever 3 categories you spent most on that month — no manual category selection", "First credit card in Canada with this mechanic", "No annual fee"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('cibc-dividend-visa-infinite', 'CIBC Dividend Visa Infinite Card', 'CIBC', 'Visa', 'cashback',
 120, '$120/yr (waived 1st year)', 21.99,
 '10% cash back for first 4 months on up to $2,500 spend, plus $50 for pre-authorized payment setup (up to $400 total value)',
 2500, 'first 4 months',
 'cashback', 'CIBC Dividend Cash Back',
 '{"gas": 4, "groceries": 4, "dining": 2, "transit": 2, "bills": 2, "other": 1}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)", "Mobile Device Insurance ($1,000)", "Travel Accident Insurance ($500,000)", "Emergency Medical Insurance ($5,000,000)", "Rental Car Theft & Damage"]'::jsonb,
 false, null,
 'Good (660-724)', '$60,000 personal / $100,000 household', false, null,
 null,
 '["4% cash back on gas & groceries", "Visa Infinite concierge and dining benefits", "Up to 10¢/L fuel savings at Journie Rewards"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$120/yr (waived 1st year)"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('cibc-dividend-visa-platinum', 'CIBC Dividend Platinum Visa Card', 'CIBC', 'Visa', 'cashback',
 99, '$99/yr (rebate available)', 21.99,
 '10% cash back for first 4 months on up to $2,000 spend (~$168 value)',
 2000, 'first 4 months',
 'cashback', 'CIBC Dividend Cash Back',
 '{"gas": 3, "groceries": 3, "dining": 2, "transit": 2, "bills": 2, "other": 1}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)", "Travel Accident Insurance ($500,000)", "Rental Car Theft & Damage"]'::jsonb,
 false, null,
 'Excellent (760-900)', '$15,000 household', false, null,
 null,
 '["3% cash back on gas & groceries", "Free Skip+ membership with $0 delivery fees", "Up to 10¢/L fuel savings at Journie Rewards"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$99/yr"}, {"label": "Supplementary card", "value": "$30/yr"}, {"label": "Cash advance", "value": "22.99% (21.99% in Quebec)"}]'::jsonb),

('cibc-dividend-visa', 'CIBC Dividend Visa Card', 'CIBC', 'Visa', 'cashback',
 0, null, 21.99,
 '5% cash back on first 4 statements, up to $2,000 spend (max $100)',
 2000, 'first 4 statements',
 'cashback', 'CIBC Dividend Cash Back',
 '{"groceries": 2, "gas": 1, "transit": 1, "dining": 1, "bills": 1, "other": 0.5}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)", "Travel Accident Insurance"]'::jsonb,
 false, null,
 'Excellent (760-900)', null, false, null,
 null,
 '["No annual fee", "2% cash back on groceries", "Lighter insurance coverage than the fee-bearing Dividend cards"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Cash advance", "value": "22.99% (21.99% in Quebec)"}]'::jsonb),

('cibc-costco-mastercard', 'CIBC Costco Mastercard', 'CIBC', 'Mastercard', 'cashback',
 0, null, 21.75,
 'Est. $477 annual rewards value for a typical Costco member',
 null, null,
 'cashback', 'CIBC Cash Back',
 '{"dining": 3, "gas": 2, "other": 1}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)", "Mobile Device Insurance ($1,000)"]'::jsonb,
 false, null,
 'Excellent (760-900)', '$15,000 personal', false, null,
 null,
 '["Requires a Costco membership", "3% at Costco gas + restaurants, 2% at Costco.ca & other gas", "Rewards paid once/year as a Costco gift certificate — redeemable only in-warehouse"]'::jsonb,
 true, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Cash advance", "value": "22.49% (21.99% in Quebec)"}, {"label": "Balance transfer", "value": "22.49% (21.99% in Quebec)"}]'::jsonb),

('cibc-us-dollar-visa', 'CIBC U.S. Dollar Aventura Gold Visa Card', 'CIBC', 'Visa', 'travel',
 35, 'US$35/yr (waived 1st year)', 21.99,
 '2,500 Aventura points (~$433 value)',
 null, null,
 'points', 'CIBC Aventura',
 '{"travel": 1, "other": 0.5}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)", "Travel Accident Insurance ($100,000)", "Rental Car Theft & Damage"]'::jsonb,
 false, null,
 'Excellent (760-900)', null, false, null,
 null,
 '["No currency conversion fee on USD purchases", "Aventura points on a USD-denominated card — unusual combination"]'::jsonb,
 false, null, null, null,
 true, 0, false,
 '[{"label": "Annual fee", "value": "US$35/yr (waived 1st year)"}, {"label": "Cash advance", "value": "22.99% (21.99% in Quebec)"}]'::jsonb),

('cibc-select-visa', 'CIBC Select Visa Card', 'CIBC', 'Visa', 'low_interest',
 29, '$29/yr (waived 1st year, then rebated 2 more years)', 13.99,
 '0% on balance transfers for 10 months (1% fee, waived in Quebec)',
 null, null,
 'none', 'None',
 '{}'::jsonb,
 '["Optional CIBC emergency travel medical insurance", "Optional payment protector insurance"]'::jsonb,
 false, null,
 'Good (660-724)', '$15,000 household', false, null,
 null,
 '["13.99% ongoing rate", "0% balance transfer for 10 months", "Instant approval available"]'::jsonb,
 true, 0, 10, 1,
 true, 2.5, true,
 '[{"label": "Annual fee", "value": "$29/yr (waived 1st year)"}, {"label": "Cash advance", "value": "13.99%"}]'::jsonb),

('cibc-classic-visa', 'CIBC Classic Visa Card', 'CIBC', 'Visa', 'rewards',
 0, null, 21.99,
 null, null, null,
 'none', 'None',
 '{}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)", "Accident Insurance"]'::jsonb,
 false, null,
 'Excellent (760-900)', '$15,000 personal', false, null,
 null,
 '["No annual fee, no-frills card", "Up to 3 additional cardholders at no cost", "3¢/L fuel discount at Journie Rewards"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Cash advance", "value": "22.99% (21.99% in Quebec)"}]'::jsonb),

('cibc-adapta-mastercard-student', 'CIBC Adapta Mastercard for Students', 'CIBC', 'Mastercard', 'rewards',
 0, null, 21.99,
 'Up to 6,000 Adapta points (~$50 value) with $1,000 spend in first 4 months',
 1000, 'first 4 months',
 'points', 'CIBC Adapta',
 '{"other": 1}'::jsonb,
 '["Roadside Assistance ($50 value)", "Extended Warranty (1 year)", "Purchase Protection (90 days)"]'::jsonb,
 false, null,
 'Fair to Good (600-724)', 'Designed for students — no formal income minimum', false, null,
 null,
 '["Student version of the Adapta Mastercard — identical rewards mechanic", "Lower credit limit for students ($5,000 domestic / $2,000 international)"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}]'::jsonb),

('cibc-dividend-visa-student', 'CIBC Dividend Visa Card for Students', 'CIBC', 'Visa', 'cashback',
 0, null, 21.99,
 '5% cash back on first 4 statements, up to $2,000 spend (max $100)',
 2000, 'first 4 statements',
 'cashback', 'CIBC Dividend Cash Back',
 '{"groceries": 2, "gas": 1, "transit": 1, "dining": 1, "bills": 1, "other": 0.5}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)"]'::jsonb,
 false, null,
 'Fair to Good (600-724)', 'Designed for students — no formal income minimum', false, null,
 null,
 '["Student version of the Dividend Visa — identical rewards and fees"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}]'::jsonb),

('cibc-aventura-visa-student', 'CIBC Aventura Visa Card for Students', 'CIBC', 'Visa', 'rewards',
 0, null, 21.99,
 'Up to 12,500 Aventura points (7,500 on first purchase, 2,500 for completing 5 activities in 60 days)',
 null, 'first 4 months',
 'points', 'CIBC Aventura',
 '{"travel": 1, "gas": 1, "groceries": 1, "drugstore": 1, "other": 0.5}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)"]'::jsonb,
 false, null,
 'Fair to Good (600-724)', 'Designed for students — no formal income minimum', false, null,
 null,
 '["Student version of the Aventura Visa — identical rewards and fees"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}]'::jsonb),

('cibc-aeroplan-visa-student', 'CIBC Aeroplan Visa Card for Students', 'CIBC', 'Visa', 'rewards',
 0, null, 21.99,
 'Up to 10,000 Aeroplan points (~$200 value)',
 null, null,
 'points', 'Aeroplan',
 '{"other": 1}'::jsonb,
 '["Limited insurance coverage (student tier)"]'::jsonb,
 false, null,
 'Fair to Good (600-724)', 'Designed for students — no formal income minimum', false, null,
 null,
 '["Student version of the Aeroplan Visa", "3¢/L fuel savings at Journie Rewards"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}]'::jsonb),

('cibc-classic-visa-student', 'CIBC Classic Visa Card for Students', 'CIBC', 'Visa', 'rewards',
 0, null, 21.99,
 null, null, null,
 'none', 'None',
 '{}'::jsonb,
 '["Extended Warranty (1 year)", "Purchase Protection (90 days)", "Accident Insurance"]'::jsonb,
 false, null,
 'Fair to Good (600-724)', 'Designed for students — no formal income minimum', false, null,
 null,
 '["Student version of the Classic Visa — no-frills, no annual fee"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}]'::jsonb)

on conflict (slug) do update set
  name = excluded.name, bank = excluded.bank, network = excluded.network,
  card_type = excluded.card_type, annual_fee = excluded.annual_fee,
  annual_fee_note = excluded.annual_fee_note, purchase_rate = excluded.purchase_rate,
  welcome_bonus_text = excluded.welcome_bonus_text, min_spend_amount = excluded.min_spend_amount,
  min_spend_period = excluded.min_spend_period, reward_type = excluded.reward_type,
  reward_program = excluded.reward_program, rewards = excluded.rewards,
  insurance = excluded.insurance, lounge_access = excluded.lounge_access,
  lounge_details = excluded.lounge_details, min_credit_score = excluded.min_credit_score,
  income_req = excluded.income_req, is_featured = excluded.is_featured,
  featured_bonus_text = excluded.featured_bonus_text, card_highlights = excluded.card_highlights,
  balance_transfer = excluded.balance_transfer, bt_rate = excluded.bt_rate,
  bt_months = excluded.bt_months, bt_fee = excluded.bt_fee,
  is_active = excluded.is_active, foreign_transaction_fee = excluded.foreign_transaction_fee,
  instant_approval = excluded.instant_approval, fees = excluded.fees;

-- ─── SCOTIABANK (17 cards, incl. 5 student variants) ─────────────────────
-- Student variants mirror their parent card's fee/rate/rewards almost
-- exactly — Scotiabank frames eligibility as "income under $12,000/yr"
-- rather than a separate product structure.

insert into credit_cards (
  slug, name, bank, network, card_type, annual_fee, annual_fee_note,
  purchase_rate, welcome_bonus_text, min_spend_amount, min_spend_period,
  reward_type, reward_program, rewards, insurance, lounge_access, lounge_details,
  min_credit_score, income_req, is_featured, featured_bonus_text,
  affiliate_link, card_highlights, balance_transfer, bt_rate, bt_months, bt_fee,
  is_active, foreign_transaction_fee, instant_approval, fees
) values

('scotiabank-passport-visa-infinite', 'Scotiabank Passport Visa Infinite+ Card', 'Scotiabank', 'Visa', 'travel',
 150, '$150/yr (waivable with Ultimate Package account)', 20.99,
 '30,000 Scene+ points ($300 travel value) with $1,000 spend in first 3 months',
 1000, 'first 3 months',
 'points', 'Scene+',
 '{"travel": 2, "other": 1}'::jsonb,
 '["Travel Emergency Medical Insurance", "Trip Cancellation/Interruption Insurance", "Flight Delay Insurance", "Baggage Insurance", "Rental Car Collision Coverage", "Mobile Device Insurance", "Purchase Security & Extended Warranty"]'::jsonb,
 true, 'Visa Airport Companion membership — 6 complimentary lounge visits/year',
 'Good (660-724)', '$60,000-$80,000 personal / $100,000-$150,000 household / $250,000-$300,000 assets', false, null,
 null,
 '["No foreign transaction fee", "6 airport lounge visits/year", "Fee fully waivable with Scotiabank Ultimate Package"]'::jsonb,
 false, null, null, null,
 true, 0, false,
 '[{"label": "Annual fee", "value": "$150/yr (waivable)"}, {"label": "Cash advance", "value": "22.99%"}, {"label": "Supplementary card", "value": "$50/yr"}]'::jsonb),

('scotiabank-momentum-visa-infinite', 'Scotia Momentum Visa Infinite+ Card', 'Scotiabank', 'Visa', 'cashback',
 120, '$120/yr (waived 1st year)', 20.99,
 '15% cash back on all purchases for first 3 months (up to $2,000 spend, ~$300 value)',
 2000, 'first 3 months',
 'cashback', 'Scotia Cash Back',
 '{"groceries": 4, "bills": 4, "gas": 2, "transit": 2, "other": 1}'::jsonb,
 '["Travel Insurance", "Mobile Device Insurance", "Trip Cancellation/Interruption Insurance", "Travel Emergency Medical Insurance", "Flight Delay Insurance", "Baggage Insurance", "Rental Car Collision Coverage", "Purchase Security & Extended Warranty"]'::jsonb,
 false, null,
 'Good (660-724)', '$60,000-$80,000 personal / $100,000-$150,000 household / $250,000-$300,000 assets', false, null,
 null,
 '["4% cash back on groceries & recurring bills", "0% intro rate on balance transfers for 12 months (2% fee)", "Concierge service included"]'::jsonb,
 true, 0, 12, 2,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$120/yr (waived 1st year)"}, {"label": "Cash advance", "value": "22.99%"}, {"label": "Supplementary card", "value": "$50/yr"}]'::jsonb),

('scotiabank-gold-american-express', 'Scotiabank Gold American Express Card', 'Scotiabank', 'Amex', 'rewards',
 120, '$120/yr (waivable with eligible bank account)', 21.99,
 'Up to 50,000 Scene+ points — 30,000 at $2,000 spend in 3 months, 20,000 at $7,500 spend in 1st year',
 2000, 'first 3 months',
 'points', 'Scene+',
 '{"groceries": 6, "dining": 5, "entertainment": 5, "travel": 4, "gas": 3, "transit": 3, "streaming": 3, "other": 1}'::jsonb,
 '["Travel Emergency Medical Insurance ($1,000,000)", "Trip Cancellation/Interruption Insurance", "Flight Delay Insurance", "Luggage Protection", "Rental Car Collision Coverage", "Mobile Device Insurance", "Purchase Security & Extended Warranty"]'::jsonb,
 true, 'Discounted Priority Pass membership — 1,200+ lounges worldwide',
 'Good (660-724)', 'Minimum personal income $12,000/yr', false, null,
 null,
 '["No foreign transaction fee (saves the typical 2.5%)", "6x points at participating grocery stores", "Discounted Priority Pass lounge membership"]'::jsonb,
 false, null, null, null,
 true, 0, false,
 '[{"label": "Annual fee", "value": "$120/yr (waivable)"}, {"label": "Cash advance", "value": "22.99%"}, {"label": "Minimum credit limit", "value": "$5,000"}]'::jsonb),

('scotiabank-scene-visa', 'Scotiabank Scene+ Visa Card', 'Scotiabank', 'Visa', 'rewards',
 0, null, 21.99,
 'Up to 5,000 Scene+ points — 2,500 at $250 spend, 2,500 more at $1,000 spend, in first 3 months',
 250, 'first 3 months',
 'points', 'Scene+',
 '{"groceries": 2, "entertainment": 2, "travel": 1, "other": 1}'::jsonb,
 '["Purchase Security & Extended Warranty Protection"]'::jsonb,
 false, null,
 'Good (660-724)', null, false, null,
 null,
 '["No annual fee", "2x points at participating grocery stores, Home Hardware & Cineplex", "Up to 25% off Avis/Budget car rentals"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('scotiabank-momentum-visa', 'Scotia Momentum Visa Card', 'Scotiabank', 'Visa', 'cashback',
 49, '$49/yr', 20.99,
 '0.99% introductory rate on balance transfers for 9 months (2% fee)',
 null, null,
 'cashback', 'Scotia Cash Back',
 '{"groceries": 2, "gas": 2, "transit": 2, "bills": 2, "streaming": 2, "other": 1}'::jsonb,
 '["Purchase Security & Extended Warranty Protection (90 days)"]'::jsonb,
 false, null,
 'Fair (560-659)', null, false, null,
 null,
 '["2% cash back across groceries, gas, transit, bills & streaming", "Up to 7¢/L value on Shell fuel purchases"]'::jsonb,
 true, 0.99, 9, 2,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$49/yr"}, {"label": "Supplementary card", "value": "$15/yr"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('scotiabank-momentum-nofee-visa', 'Scotia Momentum No-Fee Visa Card', 'Scotiabank', 'Visa', 'cashback',
 0, null, 20.99,
 '5% cash back on all purchases for first 3 months (up to $2,000 spend, ~$100 value)',
 2000, 'first 3 months',
 'cashback', 'Scotia Cash Back',
 '{"groceries": 1, "gas": 1, "transit": 1, "bills": 1, "other": 0.5}'::jsonb,
 '["Purchase Security & Extended Warranty Protection (90 days)"]'::jsonb,
 false, null,
 'Good (660-724)', null, false, null,
 null,
 '["No annual fee", "1% cash back on groceries, gas, transit & bills (capped $15,000/yr)", "0.99% intro rate on balance transfers for 9 months"]'::jsonb,
 true, 0.99, 9, 2,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('scotiabank-american-express', 'Scotiabank American Express Card', 'Scotiabank', 'Amex', 'rewards',
 0, null, 21.99,
 'Up to 10,000 Scene+ points — 2,500 at $250 spend, 7,500 more at $1,000 spend, in first 3 months',
 250, 'first 3 months',
 'points', 'Scene+',
 '{"groceries": 3, "dining": 2, "entertainment": 2, "gas": 2, "transit": 2, "streaming": 2, "travel": 1, "other": 1}'::jsonb,
 '["Mobile Device Insurance ($500)", "Purchase Security & Extended Warranty Protection"]'::jsonb,
 false, null,
 'Good (660-724)', 'Minimum personal income $12,000/yr', false, null,
 null,
 '["No annual fee", "Up to 11¢/L value on Shell fuel purchases", "Amex Offers & Experiences access"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('scotiabank-platinum-american-express', 'Scotiabank Platinum American Express Card', 'Scotiabank', 'Amex', 'premium',
 399, '$399/yr ($99 supplementary)', 9.99,
 'Up to 100,000 Scene+ points — 60,000 at $5,000 spend in 3 months, 20,000 at $10,000 spend in 6 months, 20,000 in month 14',
 5000, 'first 3 months',
 'points', 'Scene+',
 '{"travel": 2, "other": 2}'::jsonb,
 '["Travel Emergency Medical Insurance ($2M)", "Trip Cancellation/Interruption Insurance", "Flight Delay Insurance ($1,000)", "Baggage Insurance", "Rental Car Collision Coverage", "Hotel Burglary Insurance", "Travel Accident Insurance ($500,000)", "Mobile Device Insurance", "Purchase Security & Extended Warranty"]'::jsonb,
 true, '10 complimentary Priority Pass/Plaza Premium lounge visits/year (4 for supplementary cardholder)',
 'Good (660-724)', 'Minimum personal income $12,000/yr', false, null,
 null,
 '["9.99% purchase rate — unusually low for a premium card", "10 airport lounge visits/year", "No foreign transaction fee", "Automatic Hertz Club Gold membership"]'::jsonb,
 false, null, null, null,
 true, 0, false,
 '[{"label": "Annual fee", "value": "$399/yr ($99 supplementary)"}, {"label": "Cash advance", "value": "9.99%"}]'::jsonb),

('scotiabank-passport-visa-infinite-privilege', 'Scotiabank Passport Visa Infinite Privilege Card', 'Scotiabank', 'Visa', 'premium',
 599, '$599/yr ($449 with Ultimate Package)', 20.99,
 'Up to 80,000 Scene+ points — 30,000 at $3,000 spend in 3 months, 30,000 at $20,000 spend in 6 months, 20,000 in month 14',
 3000, 'first 3 months',
 'points', 'Scene+',
 '{"travel": 3, "dining": 2, "entertainment": 2, "other": 1}'::jsonb,
 '["Travel Emergency Medical Insurance ($5,000,000)", "Trip Cancellation/Interruption Insurance", "Flight Delay Insurance", "Baggage Insurance", "Rental Car Collision Coverage", "Purchase Security & Extended Warranty", "Mobile Device Insurance"]'::jsonb,
 true, '10 complimentary lounge visits/year per cardholder via Visa Airport Companion Program',
 'Good (660-724)', '$150,000 personal / $200,000 household / $400,000 assets', false, null,
 null,
 '["No foreign transaction fee", "10 airport lounge visits/year", "3x points on travel purchases"]'::jsonb,
 false, null, null, null,
 true, 0, false,
 '[{"label": "Annual fee", "value": "$599/yr ($449 with Ultimate Package)"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('scotiabank-momentum-mastercard', 'Scotia Momentum Mastercard', 'Scotiabank', 'Mastercard', 'cashback',
 0, null, 20.99,
 '7.99% introductory purchase rate for first 6 months',
 null, null,
 'cashback', 'Scotia Cash Back',
 '{"gas": 1, "groceries": 1, "drugstore": 1, "bills": 1, "other": 0.5}'::jsonb,
 '[]'::jsonb,
 false, null,
 'Excellent (760-900)', null, false, null,
 null,
 '["Accepted at Costco (Visa/Amex often aren''t)", "Up to 6¢/L value on Shell fuel purchases with Scene+", "No insurance coverage included — a rare gap for a no-fee card"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}, {"label": "Cash advance", "value": "22.99%"}]'::jsonb),

('scotiabank-us-dollar-visa', 'Scotiabank U.S. Dollar Visa Card', 'Scotiabank', 'Visa', 'travel',
 35, null, 19.99,
 null, null, null,
 'none', 'None',
 '{}'::jsonb,
 '["Purchase Security & Extended Warranty Protection (90 days, extends manufacturer warranty up to 1 year)"]'::jsonb,
 false, null,
 'Excellent (760-900)', null, false, null,
 null,
 '["No currency conversion fee on USD purchases", "Up to 5¢/L value on Shell fuel purchases"]'::jsonb,
 false, null, null, null,
 true, 0, false,
 '[{"label": "Annual fee", "value": "$35/yr"}]'::jsonb),

('scotiabank-value-visa', 'Scotiabank Value Visa Card', 'Scotiabank', 'Visa', 'low_interest',
 29, '$29/yr (waived 1st year)', 13.99,
 '0% promotional rate on balance transfers for 9 months (1% transfer fee)',
 null, null,
 'none', 'None',
 '{}'::jsonb,
 '[]'::jsonb,
 false, null,
 'Excellent (725-759)', null, false, null,
 null,
 '["13.99% ongoing rate on purchases and balance transfers", "Instant approval available", "Up to 5¢/L value on Shell fuel purchases"]'::jsonb,
 true, 0, 9, 1,
 true, 2.5, true,
 '[{"label": "Annual fee", "value": "$29/yr (waived 1st year)"}, {"label": "Cash advance", "value": "13.99%"}]'::jsonb),

('scotiabank-scene-visa-student', 'Scotiabank Scene+ Visa Card for Students', 'Scotiabank', 'Visa', 'rewards',
 0, null, 21.99,
 'Up to 5,000 Scene+ points — 2,500 at $250 spend, 2,500 more at $1,000 spend, in first 3 months',
 250, 'first 3 months',
 'points', 'Scene+',
 '{"groceries": 2, "entertainment": 2, "travel": 1, "other": 1}'::jsonb,
 '[]'::jsonb,
 false, null,
 'Fair to Good (600-724)', 'Designed for students — no formal income minimum', false, null,
 null,
 '["Student version of the Scene+ Visa — identical rewards and fees", "Good first credit card for building history"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}]'::jsonb),

('scotiabank-value-visa-student', 'Scotiabank Value Visa Card for Students', 'Scotiabank', 'Visa', 'low_interest',
 29, '$29/yr (waived 1st year)', 13.99,
 '0% promotional rate on balance transfers for 9 months (1% transfer fee)',
 null, null,
 'none', 'None',
 '{}'::jsonb,
 '[]'::jsonb,
 false, null,
 'Fair to Good (600-724)', 'Designed for students — no formal income minimum', false, null,
 null,
 '["Student version of the Value Visa — identical low ongoing rate"]'::jsonb,
 true, 0, 9, 1,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$29/yr (waived 1st year)"}]'::jsonb),

('scotiabank-momentum-visa-student', 'Scotia Momentum Visa Card for Students', 'Scotiabank', 'Visa', 'cashback',
 49, '$49/yr', 20.99,
 '0.99% introductory rate on balance transfers for 9 months (2% fee)',
 null, null,
 'cashback', 'Scotia Cash Back',
 '{"groceries": 2, "gas": 2, "transit": 2, "bills": 2, "streaming": 2, "other": 1}'::jsonb,
 '["Purchase Security & Extended Warranty Protection (90 days)"]'::jsonb,
 false, null,
 'Fair to Good (600-724)', 'Designed for students — no formal income minimum', false, null,
 null,
 '["Student version of the Momentum Visa — identical rewards and fees"]'::jsonb,
 true, 0.99, 9, 2,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$49/yr"}]'::jsonb),

('scotiabank-momentum-nofee-visa-student', 'Scotia Momentum No-Fee Visa Card for Students', 'Scotiabank', 'Visa', 'cashback',
 0, null, 20.99,
 '5% cash back on all purchases for first 3 months (up to $2,000 spend, ~$100 value)',
 2000, 'first 3 months',
 'cashback', 'Scotia Cash Back',
 '{"groceries": 1, "gas": 1, "transit": 1, "bills": 1, "other": 0.5}'::jsonb,
 '["Purchase Security & Extended Warranty Protection (90 days)"]'::jsonb,
 false, null,
 'Fair to Good (600-724)', 'Designed for students — no formal income minimum', false, null,
 null,
 '["Student version of the Momentum No-Fee Visa — identical rewards and fees", "No annual fee"]'::jsonb,
 true, 0.99, 9, 2,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}]'::jsonb),

('scotiabank-american-express-student', 'Scotiabank American Express Card for Students', 'Scotiabank', 'Amex', 'rewards',
 0, null, 21.99,
 'Up to 10,000 Scene+ points — 2,500 at $250 spend, 7,500 more at $1,000 spend, in first 3 months',
 250, 'first 3 months',
 'points', 'Scene+',
 '{"groceries": 3, "dining": 2, "entertainment": 2, "gas": 2, "transit": 2, "streaming": 2, "travel": 1, "other": 1}'::jsonb,
 '["Mobile Device Insurance ($500)", "Purchase Security & Extended Warranty Protection"]'::jsonb,
 false, null,
 'Fair to Good (600-724)', 'Minimum personal income $12,000/yr (students)', false, null,
 null,
 '["Student version of the Scotiabank Amex — identical rewards and fees", "Up to 11¢/L value on Shell fuel purchases"]'::jsonb,
 false, null, null, null,
 true, 2.5, false,
 '[{"label": "Annual fee", "value": "$0"}]'::jsonb)

on conflict (slug) do update set
  name = excluded.name, bank = excluded.bank, network = excluded.network,
  card_type = excluded.card_type, annual_fee = excluded.annual_fee,
  annual_fee_note = excluded.annual_fee_note, purchase_rate = excluded.purchase_rate,
  welcome_bonus_text = excluded.welcome_bonus_text, min_spend_amount = excluded.min_spend_amount,
  min_spend_period = excluded.min_spend_period, reward_type = excluded.reward_type,
  reward_program = excluded.reward_program, rewards = excluded.rewards,
  insurance = excluded.insurance, lounge_access = excluded.lounge_access,
  lounge_details = excluded.lounge_details, min_credit_score = excluded.min_credit_score,
  income_req = excluded.income_req, is_featured = excluded.is_featured,
  featured_bonus_text = excluded.featured_bonus_text, card_highlights = excluded.card_highlights,
  balance_transfer = excluded.balance_transfer, bt_rate = excluded.bt_rate,
  bt_months = excluded.bt_months, bt_fee = excluded.bt_fee,
  is_active = excluded.is_active, foreign_transaction_fee = excluded.foreign_transaction_fee,
  instant_approval = excluded.instant_approval, fees = excluded.fees;


-- ─── WEALTHSIMPLE (1 card) ────────────────────────────────────────────────
-- Credit score is an inference (725-759), not directly sourced — no
-- dedicated creditcardgenius.ca review page exists yet for this card
-- (launched ~Oct 2025), so this is estimated from its income requirement
-- matching similar premium-tier peers. Flagging for spot-check later.

insert into credit_cards (
  slug, name, bank, network, card_type, annual_fee, annual_fee_note,
  purchase_rate, welcome_bonus_text, min_spend_amount, min_spend_period,
  reward_type, reward_program, rewards, insurance, lounge_access, lounge_details,
  min_credit_score, income_req, is_featured, featured_bonus_text,
  affiliate_link, card_highlights, balance_transfer, is_active,
  foreign_transaction_fee, instant_approval
) values

('wealthsimple-visa-infinite-privilege', 'Wealthsimple Cashback Visa Infinite Privilege Card', 'Wealthsimple', 'Visa', 'cashback',
 0, '$20/mo, waived for qualifying Wealthsimple clients', 20.99,
 'Not stated',
 null, null,
 'cashback', 'Wealthsimple Cash Back',
 '{"other": 2}'::jsonb,
 '["Mobile Device Insurance", "Purchase Protection", "Extended Warranty", "Travel Protection", "Car Rental Insurance", "Flight Delay Insurance"]'::jsonb,
 true, '1,200+ airport lounges (Visa Infinite Privilege tier only)',
 'Excellent (725-759)', '$150,000 personal / $200,000 household (or $50,000 annual spend, or $400,000 in assets) for Privilege tier; $80,000 personal / $150,000 household for base Infinite+ tier', false, null,
 null,
 '["Flat 2% cash back on everything — no categories to track", "0% foreign transaction fee", "Fee waived by holding qualifying Wealthsimple assets, not a fixed annual charge"]'::jsonb,
 false, true, 0, false)

on conflict (slug) do update set
  name = excluded.name, bank = excluded.bank, network = excluded.network,
  card_type = excluded.card_type, annual_fee = excluded.annual_fee,
  annual_fee_note = excluded.annual_fee_note, purchase_rate = excluded.purchase_rate,
  welcome_bonus_text = excluded.welcome_bonus_text, min_spend_amount = excluded.min_spend_amount,
  min_spend_period = excluded.min_spend_period, reward_type = excluded.reward_type,
  reward_program = excluded.reward_program, rewards = excluded.rewards,
  insurance = excluded.insurance, lounge_access = excluded.lounge_access,
  lounge_details = excluded.lounge_details, min_credit_score = excluded.min_credit_score,
  income_req = excluded.income_req, is_featured = excluded.is_featured,
  featured_bonus_text = excluded.featured_bonus_text, card_highlights = excluded.card_highlights,
  balance_transfer = excluded.balance_transfer, is_active = excluded.is_active,
  foreign_transaction_fee = excluded.foreign_transaction_fee,
  instant_approval = excluded.instant_approval;
