// ─── LEGAL CONTENT ────────────────────────────────────────────────────────
// Generic Terms of Service and Privacy Policy for a Canadian credit-card
// comparison platform with AI-powered features and affiliate revenue.
// This is a reasonable starting template, not a substitute for review by
// a lawyer licensed in your province — update the contact/jurisdiction
// details before treating this as final.

export type LegalSection = { heading: string; body: string[] };
export type LegalDoc = {
  title: string;
  effectiveDate: string;
  intro: string;
  sections: LegalSection[];
};

const EFFECTIVE_DATE = "August 17, 2026";

export const TERMS_OF_SERVICE: LegalDoc = {
  title: "Terms of Service",
  effectiveDate: EFFECTIVE_DATE,
  intro:
    "These Terms of Service (\"Terms\") govern your access to and use of CreditMind (\"CreditMind,\" \"we,\" \"us,\" or \"our\"), including our website, mobile app, and related tools. By using CreditMind, you agree to these Terms. If you don't agree, please don't use the service.",
  sections: [
    {
      heading: "1. What CreditMind is — and isn't",
      body: [
        "CreditMind is an informational platform that helps you compare Canadian credit cards and understand your credit and debt options. We are not a bank, lender, credit union, or credit broker. We do not issue credit cards, extend credit, or make lending decisions of any kind.",
        "Nothing on CreditMind is financial, legal, or tax advice. The information, comparisons, scores, and recommendations we provide are for general informational purposes only and should not be relied on as the sole basis for any financial decision. Always review a card issuer's own terms, rates, and disclosures before applying, and consult a licensed financial advisor for advice specific to your situation.",
      ],
    },
    {
      heading: "2. AI-powered features",
      body: [
        "CreditMind uses artificial intelligence and machine learning models to power certain features, including the AI Educator chat, the Stack Optimizer, the Debt Optimizer, and card-matching recommendations from the quiz. This is a required disclosure: any response, score, recommendation, or explanation generated by these features is produced by an AI system, not a human financial advisor.",
        "AI-generated content can be incomplete, outdated, or simply wrong. Card rates, fees, and welcome offers change frequently — always confirm current terms directly on the issuer's official page before applying or making a decision based on anything CreditMind's AI features tell you.",
        "Do not enter sensitive personal information — such as your Social Insurance Number, full account numbers, or passwords — into the AI Educator chat or any other feature on the platform.",
      ],
    },
    {
      heading: "3. How we make money (advertiser disclosure)",
      body: [
        "CreditMind may receive compensation from credit card issuers and their partners when you click on, apply for, or are approved for a card through a link on our site. This is how we keep the comparison tools free to use.",
        "This compensation may influence which cards we mark as \"Featured\" or how offers are surfaced on the site. It does not influence the factual details we publish about a card (fees, rates, rewards, etc.), which we source directly from issuers and independent research. Whether or not a card pays us anything, our goal is for the underlying information to be accurate — but you should still independently verify terms with the issuer, since rates and offers can change without notice.",
      ],
    },
    {
      heading: "4. Eligibility and accounts",
      body: [
        "You must have reached the age of majority in your province or territory to create an account. If you create an account, you're responsible for keeping your login credentials secure and for all activity that happens under your account. Let us know right away if you suspect unauthorized access.",
        "You agree to provide accurate information when creating an account or using tools like the Debt Optimizer, and to keep it reasonably up to date.",
      ],
    },
    {
      heading: "5. Acceptable use",
      body: [
        "You agree not to: scrape or systematically extract data from the site without our written permission; attempt to reverse-engineer, decompile, or interfere with the platform's normal operation; use the service for any unlawful purpose; impersonate another person or misrepresent your affiliation with anyone; or attempt to gain unauthorized access to any part of the service, other accounts, or connected systems.",
      ],
    },
    {
      heading: "6. Intellectual property",
      body: [
        "The CreditMind name, logo, and all site content we create — including card comparisons, editorial write-ups, design, and software — are owned by CreditMind or our licensors and protected by copyright and trademark law. You may use the site for personal, non-commercial purposes, but you may not copy, republish, or redistribute our content without permission.",
        "Card names, issuer logos, and product details referenced on this site belong to their respective owners and are used for identification and comparison purposes only. CreditMind is not affiliated with, endorsed by, or sponsored by any bank or card issuer unless explicitly stated.",
      ],
    },
    {
      heading: "7. Third-party links",
      body: [
        "CreditMind links out to credit card issuers' own websites and application pages. We don't control those sites and aren't responsible for their content, terms, or privacy practices. Once you leave CreditMind, that issuer's own terms and privacy policy apply.",
      ],
    },
    {
      heading: "8. Disclaimer of warranties",
      body: [
        "CreditMind is provided \"as is\" and \"as available,\" without warranties of any kind, express or implied, including implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We don't guarantee that the service will be uninterrupted, error-free, secure, or that any information (including rates, fees, or AI-generated content) is complete, current, or accurate.",
      ],
    },
    {
      heading: "9. Limitation of liability",
      body: [
        "To the fullest extent permitted by law, CreditMind and its owners, employees, and partners will not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits, revenue, data, or credit opportunities, arising from your use of — or inability to use — the service, including reliance on AI-generated content or card information that later turns out to be inaccurate or outdated.",
      ],
    },
    {
      heading: "10. Termination",
      body: [
        "We may suspend or terminate your access to CreditMind at any time, with or without notice, if we believe you've violated these Terms or for any other reason at our discretion. You may stop using the service or delete your account at any time.",
      ],
    },
    {
      heading: "11. Changes to these Terms",
      body: [
        "We may update these Terms from time to time. If we make material changes, we'll update the effective date above and, where appropriate, provide additional notice. Continuing to use CreditMind after changes take effect means you accept the updated Terms.",
      ],
    },
    {
      heading: "12. Governing law",
      body: [
        "These Terms are governed by the laws of the Province of Ontario and the federal laws of Canada applicable therein, without regard to conflict-of-law principles.",
      ],
    },
    {
      heading: "13. Contact us",
      body: [
        "Questions about these Terms? Reach us at legal@creditmind.ca.",
      ],
    },
  ],
};

export const PRIVACY_POLICY: LegalDoc = {
  title: "Privacy Policy",
  effectiveDate: EFFECTIVE_DATE,
  intro:
    "This Privacy Policy explains how CreditMind (\"we,\" \"us,\" or \"our\") collects, uses, discloses, and protects your personal information when you use our website, app, and tools. We built CreditMind to follow Canadian privacy law, including the Personal Information Protection and Electronic Documents Act (PIPEDA). By using CreditMind, you agree to the practices described here.",
  sections: [
    {
      heading: "1. Information we collect",
      body: [
        "Account information: if you create an account, we collect your email address and any profile details you provide (like a referral code or push notification preference).",
        "Financial inputs you choose to give us: tools like the Stack Optimizer and Debt Optimizer ask for information you voluntarily enter — for example, which cards you hold, spending amounts by category, or debt balances — so we can generate a recommendation. We do not ask for or store full account numbers, SINs, or banking credentials, and you should never enter that information into any field on the site.",
        "Usage data: pages you visit, cards you view or compare, quiz answers, and general interaction data, collected automatically to help us understand how the site is used.",
        "Device and log data: IP address, browser type, device type, and similar technical information, collected automatically for security and diagnostics.",
        "Cookies and similar technologies: used to keep you signed in, remember preferences, and understand aggregate usage patterns. You can control cookies through your browser settings.",
      ],
    },
    {
      heading: "2. How we use your information",
      body: [
        "To provide and operate the service — comparing cards, running the quiz, generating Stack/Debt Optimizer results, and maintaining your account.",
        "To personalize your experience, such as showing you your saved card stack or watchlist.",
        "To communicate with you about your account, respond to support requests, and (only with your consent, where required) send product updates.",
        "To maintain the security and integrity of the platform, detect fraud or abuse, and comply with legal obligations.",
        "To improve CreditMind over time, including understanding which features are useful and where the AI-generated recommendations need improvement.",
      ],
    },
    {
      heading: "3. AI and automated processing",
      body: [
        "When you use AI-powered features — the AI Educator chat, the Stack Optimizer, the Debt Optimizer, or the card-matching quiz — the information you provide in that interaction (such as your question, spending inputs, or debt figures) is sent to a third-party AI model provider to generate a response. That provider processes the data solely to generate your response and under its own data-handling terms.",
        "Do not share sensitive personal information (SIN, full account numbers, passwords, or anyone else's personal information) in chat or optimizer inputs. Treat these tools like you would a search engine, not a secure banking channel.",
      ],
    },
    {
      heading: "4. How we share your information",
      body: [
        "Service providers: we use third parties to run the platform, including Supabase (database and authentication hosting) and AI model providers (to power AI features). These providers only receive the data needed to perform their function and are contractually restricted from using it for anything else.",
        "Card issuers: if you click through to apply for a card, the issuer's own site takes over and collects information directly from you under their own privacy policy — we don't share your CreditMind account data with issuers just because you viewed or compared their card.",
        "Legal requirements: we may disclose information if required by law, court order, or to protect the rights, safety, or property of CreditMind or others.",
        "Business transfers: if CreditMind is involved in a merger, acquisition, or sale of assets, your information may be transferred as part of that transaction, subject to this policy or a successor policy.",
        "We do not sell your personal information.",
      ],
    },
    {
      heading: "5. Data retention",
      body: [
        "We keep your personal information for as long as your account is active or as needed to provide the service, comply with legal obligations, resolve disputes, and enforce our agreements. You can request deletion of your account and associated data at any time (see \"Your rights\" below).",
      ],
    },
    {
      heading: "6. Data security",
      body: [
        "We use reasonable technical and organizational safeguards — including encryption in transit and access controls — to protect your information. No system is perfectly secure, and we can't guarantee absolute security, but we take reasonable steps to protect your data from unauthorized access, loss, or misuse.",
      ],
    },
    {
      heading: "7. Your rights and choices",
      body: [
        "Under Canadian privacy law, you generally have the right to access the personal information we hold about you, correct inaccuracies, withdraw consent for certain uses, and request deletion of your account and data. To exercise any of these rights, contact us at privacy@creditmind.ca.",
        "You can also manage cookie preferences through your browser and opt out of non-essential email communications at any time via the unsubscribe link in those emails.",
      ],
    },
    {
      heading: "8. Children's privacy",
      body: [
        "CreditMind is not directed at, and we do not knowingly collect personal information from, children under the age of majority in their province or territory. If you believe a minor has provided us with personal information, contact us and we'll remove it.",
      ],
    },
    {
      heading: "9. International data transfers",
      body: [
        "Some of our service providers (including hosting and AI model providers) may process data outside of Canada, including in the United States. Where that happens, your information may become subject to the laws of that jurisdiction, including lawful access requests by foreign authorities.",
      ],
    },
    {
      heading: "10. Changes to this policy",
      body: [
        "We may update this Privacy Policy from time to time. If we make material changes, we'll update the effective date above and, where appropriate, notify you through the site or by email.",
      ],
    },
    {
      heading: "11. Contact us",
      body: [
        "Questions, requests, or concerns about this Privacy Policy or your personal information? Reach our privacy team at privacy@creditmind.ca.",
      ],
    },
  ],
};
